// Publishes the supplied brand sources into public/brand and writes a typed manifest.
// Sources in assets/source are never modified. public/brand is generated and ignored by Git.
import { createHash } from 'node:crypto'
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { basename, extname, join, relative } from 'node:path'

const check = process.argv.includes('--check')
const logoRoot = 'assets/source/Convert_Logos_2024'
const stackRoot = 'assets/source/CD_Stacks'
const publicRoot = 'public/brand'
const manifestFile = 'src/brand/assets.generated.ts'

const colourNames = ['Dark Green', 'Light Green', 'White', 'Black']
const formats = { '.svg': 'svg', '.png': 'png', '.jpg': 'jpg' }

const slug = (value) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

function walk(dir) {
  return readdirSync(dir)
    .sort()
    .flatMap((name) => {
      const path = join(dir, name)
      return statSync(path).isDirectory() ? walk(path) : [path]
    })
}

function svgGeometry(svg, file) {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]
  const fill = svg.match(/fill:\s*(#[0-9a-fA-F]{6})/)?.[1] ?? svg.match(/fill="(#[0-9a-fA-F]{6})"/)?.[1]
  const shapes = [...svg.matchAll(/<(path|rect|polygon)\b([^>]*)\/>/g)].map(([, tag, attrs]) => {
    const attr = (name) => attrs.match(new RegExp(`\\b${name}="([^"]*)"`))?.[1]
    if (tag === 'path') return { tag, d: attr('d') }
    if (tag === 'polygon') return { tag, points: attr('points').trim().replace(/\s+/g, ' ') }
    return { tag, x: attr('x') ?? '0', y: attr('y') ?? '0', width: attr('width'), height: attr('height') }
  })
  if (!viewBox || !fill || shapes.length === 0) throw new Error(`${file}: could not read geometry`)
  return { viewBox, fill: fill.toLowerCase(), shapes }
}

const logos = walk(logoRoot)
  .filter((path) => formats[extname(path).toLowerCase()])
  .map((path) => {
    const rel = relative(logoRoot, path)
    const parts = rel.split('/')
    const family = parts[0] === 'Profile Icons' ? 'Profile icon' : parts[0]
    const clearSpace = rel.includes('Clear Space')
    const format = formats[extname(path).toLowerCase()]
    const name = basename(path, extname(path))
    const colour = colourNames.find((c) => name.includes(c)) ?? null
    const bytes = readFileSync(path)
    const publicPath = `brand/logos/${slug(rel.replace(extname(rel), ''))}.${format}`
    const asset = {
      id: slug(rel.replace(extname(rel), '')),
      family,
      label: family === 'Profile icon' ? name.replace(/_/g, ' ') : `${family}${clearSpace ? ', clear space' : ''}`,
      colour,
      format,
      clearSpace,
      source: rel,
      href: `/${publicPath}`,
      bytes: bytes.length,
      sha256: createHash('sha256').update(bytes).digest('hex'),
    }
    if (format === 'svg') asset.geometry = svgGeometry(bytes.toString('utf8'), rel)
    return { asset, path, publicPath }
  })

const stackFiles = walk(stackRoot).filter((path) => path.endsWith('.svg'))

const output = `// Generated by scripts/build-assets.mjs. Do not edit.
import type { BrandAsset } from './asset-types'

export const logoAssets: readonly BrandAsset[] = ${JSON.stringify(
  logos.map((l) => l.asset),
  null,
  2,
)}
`

if (check) {
  if (readFileSync(manifestFile, 'utf8') !== output) {
    console.error(`${manifestFile} is out of date. Run pnpm assets.`)
    process.exit(1)
  }
} else {
  writeFileSync(manifestFile, output)
}

rmSync(publicRoot, { recursive: true, force: true })
for (const { path, publicPath } of logos) {
  mkdirSync(join('public', publicPath, '..'), { recursive: true })
  cpSync(path, join('public', publicPath))
}
mkdirSync(join(publicRoot, 'stacks'), { recursive: true })
for (const path of stackFiles) cpSync(path, join(publicRoot, 'stacks', basename(path).toLowerCase().replace(/_/g, '-')))
console.log(`Published ${logos.length} logo files and ${stackFiles.length} stacks to ${publicRoot}`)
