// Reads the supplied stack SVGs and writes their geometry to a typed module.
// Fails if any source file departs from the audited shape: three paths, one fill, no transforms.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const sourceDir = 'assets/source/CD_Stacks'
const outFile = 'src/brand/stacks.generated.ts'
const check = process.argv.includes('--check')

const files = readdirSync(sourceDir)
  .filter((name) => name.endsWith('.svg'))
  .sort()

const stacks = files.map((file) => {
  const svg = readFileSync(join(sourceDir, file), 'utf8')
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]
  const paths = [...svg.matchAll(/<path d="([^"]+)" fill="([^"]+)"\s*\/>/g)]
  const fills = new Set(paths.map((match) => match[2].toLowerCase()))
  if (!viewBox) throw new Error(`${file}: missing viewBox`)
  if (paths.length !== 3) throw new Error(`${file}: expected 3 paths, found ${paths.length}`)
  if (fills.size !== 1) throw new Error(`${file}: expected one fill, found ${[...fills].join(', ')}`)
  if (/transform|<g|<rect|<polygon|stroke=/.test(svg)) throw new Error(`${file}: unexpected element or attribute`)
  const [, , width, height] = viewBox.split(/\s+/).map(Number)
  const number = file.match(/(\d+)/)?.[1]
  return { id: `stack-${number}`, label: `Stack ${number}`, file, width, height, paths: paths.map((m) => m[1]) }
})

const output = `// Generated by scripts/build-stacks.mjs from ${sourceDir}. Do not edit.
import type { StackArtwork } from './stack-types'

export const stacks: readonly StackArtwork[] = ${JSON.stringify(stacks, null, 2)}
`

if (check) {
  const current = readFileSync(outFile, 'utf8')
  if (current !== output) {
    console.error(`${outFile} is out of date. Run pnpm stacks.`)
    process.exit(1)
  }
  console.log(`${stacks.length} stacks match ${outFile}`)
} else {
  writeFileSync(outFile, output)
  console.log(`Wrote ${stacks.length} stacks to ${outFile}`)
}
