// Generated by scripts/build-assets.mjs. Do not edit.
import type { BrandAsset } from './asset-types'

export const logoAssets: readonly BrandAsset[] = [
  {
    "id": "icon-jpeg-clear-space-convert-icon-clear-space-black",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "Black",
    "format": "jpg",
    "clearSpace": true,
    "source": "Icon/JPEG/Clear Space/Convert_Icon_Clear Space_Black.jpg",
    "href": "/brand/logos/icon-jpeg-clear-space-convert-icon-clear-space-black.jpg",
    "bytes": 42084,
    "sha256": "fdaaeeabc898caceed01a3bf34448d045dfa73f6c0b24fdb999248f185ca7a63"
  },
  {
    "id": "icon-jpeg-clear-space-convert-icon-clear-space-dark-green",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "Dark Green",
    "format": "jpg",
    "clearSpace": true,
    "source": "Icon/JPEG/Clear Space/Convert_Icon_Clear Space_Dark Green.jpg",
    "href": "/brand/logos/icon-jpeg-clear-space-convert-icon-clear-space-dark-green.jpg",
    "bytes": 42751,
    "sha256": "4dcdc81c71eca71082b915d49589c9addb1f86ae53d7d8be455440c5e74f7432"
  },
  {
    "id": "icon-jpeg-clear-space-convert-icon-clear-space-light-green",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "Light Green",
    "format": "jpg",
    "clearSpace": true,
    "source": "Icon/JPEG/Clear Space/Convert_Icon_Clear Space_Light Green.jpg",
    "href": "/brand/logos/icon-jpeg-clear-space-convert-icon-clear-space-light-green.jpg",
    "bytes": 49328,
    "sha256": "9e793bba1f4105f158a2c2e662c264f37e2f65b4dc0d3de35fc90b1157db40e2"
  },
  {
    "id": "icon-jpeg-clear-space-convert-icon-clear-space-white",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "White",
    "format": "jpg",
    "clearSpace": true,
    "source": "Icon/JPEG/Clear Space/Convert_Icon_Clear Space_White.jpg",
    "href": "/brand/logos/icon-jpeg-clear-space-convert-icon-clear-space-white.jpg",
    "bytes": 36444,
    "sha256": "67f5b7dfb37e89d7b13cc251b30da206f4ec1a4bfefeb2bf67ba06f107b8904b"
  },
  {
    "id": "icon-jpeg-convert-icon-black",
    "family": "Icon",
    "label": "Icon",
    "colour": "Black",
    "format": "jpg",
    "clearSpace": false,
    "source": "Icon/JPEG/Convert_Icon_Black.jpg",
    "href": "/brand/logos/icon-jpeg-convert-icon-black.jpg",
    "bytes": 15169,
    "sha256": "dbc38f94e0b655ebba3e696bcc326bccf31d8931ba32e37d68655ba7ebe0d9a0"
  },
  {
    "id": "icon-jpeg-convert-icon-dark-green",
    "family": "Icon",
    "label": "Icon",
    "colour": "Dark Green",
    "format": "jpg",
    "clearSpace": false,
    "source": "Icon/JPEG/Convert_Icon_Dark Green.jpg",
    "href": "/brand/logos/icon-jpeg-convert-icon-dark-green.jpg",
    "bytes": 16788,
    "sha256": "5ca2862750d24eed21038a98edf167c9a85c65dfd3ff51a9116fd132fbf89cab"
  },
  {
    "id": "icon-jpeg-convert-icon-light-green",
    "family": "Icon",
    "label": "Icon",
    "colour": "Light Green",
    "format": "jpg",
    "clearSpace": false,
    "source": "Icon/JPEG/Convert_Icon_Light Green.jpg",
    "href": "/brand/logos/icon-jpeg-convert-icon-light-green.jpg",
    "bytes": 24505,
    "sha256": "e179852147af7eab377a27feed54a79bc0a1ce8454c01bef08f9b90fa63fd836"
  },
  {
    "id": "icon-jpeg-convert-icon-white",
    "family": "Icon",
    "label": "Icon",
    "colour": "White",
    "format": "jpg",
    "clearSpace": false,
    "source": "Icon/JPEG/Convert_Icon_White.jpg",
    "href": "/brand/logos/icon-jpeg-convert-icon-white.jpg",
    "bytes": 12788,
    "sha256": "d7c04b5eb7377342490de54de5a3702b421232d414eeb99885a5424ffbde1bdd"
  },
  {
    "id": "icon-png-clear-space-convert-icon-clear-space-black",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "Black",
    "format": "png",
    "clearSpace": true,
    "source": "Icon/PNG/Clear Space/Convert_Icon_Clear Space_Black.png",
    "href": "/brand/logos/icon-png-clear-space-convert-icon-clear-space-black.png",
    "bytes": 11995,
    "sha256": "8f6e207ec14d7120f488cb118c8cf5670aab37976a9dc3891d199a0da572e57a"
  },
  {
    "id": "icon-png-clear-space-convert-icon-clear-space-dark-green",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "Dark Green",
    "format": "png",
    "clearSpace": true,
    "source": "Icon/PNG/Clear Space/Convert_Icon_Clear Space_Dark Green.png",
    "href": "/brand/logos/icon-png-clear-space-convert-icon-clear-space-dark-green.png",
    "bytes": 11995,
    "sha256": "58e4c45d75758aa980b3124a5bc787f7a5ae4a2069adce6f990bfcd0bb0f9d95"
  },
  {
    "id": "icon-png-clear-space-convert-icon-clear-space-light-green",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "Light Green",
    "format": "png",
    "clearSpace": true,
    "source": "Icon/PNG/Clear Space/Convert_Icon_Clear Space_Light Green.png",
    "href": "/brand/logos/icon-png-clear-space-convert-icon-clear-space-light-green.png",
    "bytes": 12002,
    "sha256": "f1861004db968d8be7eaf5f5eaae8838818e15f47f2938eeca21ba5a180a55cf"
  },
  {
    "id": "icon-png-clear-space-convert-icon-clear-space-white",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "White",
    "format": "png",
    "clearSpace": true,
    "source": "Icon/PNG/Clear Space/Convert_Icon_Clear Space_White.png",
    "href": "/brand/logos/icon-png-clear-space-convert-icon-clear-space-white.png",
    "bytes": 11992,
    "sha256": "5d4a3c918f1d37f796755f0f8fe14c9a644feff24a4f9a832533dfc408eb1b5a"
  },
  {
    "id": "icon-png-convert-icon-black",
    "family": "Icon",
    "label": "Icon",
    "colour": "Black",
    "format": "png",
    "clearSpace": false,
    "source": "Icon/PNG/Convert_Icon_Black.png",
    "href": "/brand/logos/icon-png-convert-icon-black.png",
    "bytes": 2399,
    "sha256": "f05a63e89ad14d769918ea05b26ab03198dda1f46e3b36ec366f93bb50161023"
  },
  {
    "id": "icon-png-convert-icon-dark-green",
    "family": "Icon",
    "label": "Icon",
    "colour": "Dark Green",
    "format": "png",
    "clearSpace": false,
    "source": "Icon/PNG/Convert_Icon_Dark Green.png",
    "href": "/brand/logos/icon-png-convert-icon-dark-green.png",
    "bytes": 2403,
    "sha256": "11dcf3e96e01e063296c193bdb3ab85fc0c54d7cc9a4aed493e080380b1b9ed6"
  },
  {
    "id": "icon-png-convert-icon-light-green",
    "family": "Icon",
    "label": "Icon",
    "colour": "Light Green",
    "format": "png",
    "clearSpace": false,
    "source": "Icon/PNG/Convert_Icon_Light Green.png",
    "href": "/brand/logos/icon-png-convert-icon-light-green.png",
    "bytes": 2401,
    "sha256": "4511fa7ec58fba31c9c508b680e2410106fe3b95915488590fcc38027038ad9a"
  },
  {
    "id": "icon-png-convert-icon-white",
    "family": "Icon",
    "label": "Icon",
    "colour": "White",
    "format": "png",
    "clearSpace": false,
    "source": "Icon/PNG/Convert_Icon_White.png",
    "href": "/brand/logos/icon-png-convert-icon-white.png",
    "bytes": 2405,
    "sha256": "153275eb48db6f00615717fa5ee80e4a9d0e96834b5242bc6f6a5bb4eefde370"
  },
  {
    "id": "icon-svg-clear-space-convert-icon-clear-space-black",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "Black",
    "format": "svg",
    "clearSpace": true,
    "source": "Icon/SVG/Clear Space/Convert_Icon_Clear Space_Black.svg",
    "href": "/brand/logos/icon-svg-clear-space-convert-icon-clear-space-black.svg",
    "bytes": 585,
    "sha256": "96bf935ad844ce8f739ade7e48c872d506ea83b4b4ce326eec91fa1dd419b07e",
    "geometry": {
      "viewBox": "0 0 338.7 362.2",
      "fill": "#231f20",
      "shapes": [
        {
          "tag": "path",
          "d": "M136.4,249.3h89.4v-23.5h-89.4V249.3z M112.9,225.8h23.5v-89.4h-23.5C112.9,136.4,112.9,225.8,112.9,225.8z\n\t M136.4,136.4h89.4v-23.5h-89.4V136.4z"
        }
      ]
    }
  },
  {
    "id": "icon-svg-clear-space-convert-icon-clear-space-dark-green",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "Dark Green",
    "format": "svg",
    "clearSpace": true,
    "source": "Icon/SVG/Clear Space/Convert_Icon_Clear Space_Dark Green.svg",
    "href": "/brand/logos/icon-svg-clear-space-convert-icon-clear-space-dark-green.svg",
    "bytes": 585,
    "sha256": "881329836b063828a1dd76d227c8bd378ee9351bd77006f672b109c43ffd736f",
    "geometry": {
      "viewBox": "0 0 338.7 362.2",
      "fill": "#27382f",
      "shapes": [
        {
          "tag": "path",
          "d": "M136.4,249.3h89.4v-23.5h-89.4V249.3z M112.9,225.8h23.5v-89.4h-23.5C112.9,136.4,112.9,225.8,112.9,225.8z\n\t M136.4,136.4h89.4v-23.5h-89.4V136.4z"
        }
      ]
    }
  },
  {
    "id": "icon-svg-clear-space-convert-icon-clear-space-light-green",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "Light Green",
    "format": "svg",
    "clearSpace": true,
    "source": "Icon/SVG/Clear Space/Convert_Icon_Clear Space_Light Green.svg",
    "href": "/brand/logos/icon-svg-clear-space-convert-icon-clear-space-light-green.svg",
    "bytes": 585,
    "sha256": "eacfc1af078a9e00c0adea48987154f81f9621e7f8c641c55c99b140ae40223b",
    "geometry": {
      "viewBox": "0 0 338.7 362.2",
      "fill": "#c9deb6",
      "shapes": [
        {
          "tag": "path",
          "d": "M136.4,249.3h89.4v-23.5h-89.4V249.3z M112.9,225.8h23.5v-89.4h-23.5C112.9,136.4,112.9,225.8,112.9,225.8z\n\t M136.4,136.4h89.4v-23.5h-89.4V136.4z"
        }
      ]
    }
  },
  {
    "id": "icon-svg-clear-space-convert-icon-clear-space-white",
    "family": "Icon",
    "label": "Icon, clear space",
    "colour": "White",
    "format": "svg",
    "clearSpace": true,
    "source": "Icon/SVG/Clear Space/Convert_Icon_Clear Space_White.svg",
    "href": "/brand/logos/icon-svg-clear-space-convert-icon-clear-space-white.svg",
    "bytes": 555,
    "sha256": "e5a0b5ec7f149ec76fd521dc3263389cc0fc55ada91ff8c4d0ff44d88fadbcfe",
    "geometry": {
      "viewBox": "0 0 338.7 362.2",
      "fill": "#faf9f7",
      "shapes": [
        {
          "tag": "path",
          "d": "M136.4,249.3h89.4v-23.5h-89.4V249.3z M112.9,225.8h23.5v-89.4h-23.5V225.8z M136.4,136.4h89.4v-23.5h-89.4\n\tV136.4z"
        }
      ]
    }
  },
  {
    "id": "icon-svg-convert-icon-black",
    "family": "Icon",
    "label": "Icon",
    "colour": "Black",
    "format": "svg",
    "clearSpace": false,
    "source": "Icon/SVG/Convert_Icon_Black.svg",
    "href": "/brand/logos/icon-svg-convert-icon-black.svg",
    "bytes": 534,
    "sha256": "4ea79dabb8c69d9517bb12f7b720265bc30d5aaf942a35a235962ab7d8128c25",
    "geometry": {
      "viewBox": "0 0 112.9 136.4",
      "fill": "#231f20",
      "shapes": [
        {
          "tag": "path",
          "d": "M23.5,136.4h89.4v-23.5H23.5V136.4z M0,112.9h23.5V23.5H0V112.9z M23.5,23.5h89.4V0H23.5V23.5z"
        }
      ]
    }
  },
  {
    "id": "icon-svg-convert-icon-dark-green",
    "family": "Icon",
    "label": "Icon",
    "colour": "Dark Green",
    "format": "svg",
    "clearSpace": false,
    "source": "Icon/SVG/Convert_Icon_Dark Green.svg",
    "href": "/brand/logos/icon-svg-convert-icon-dark-green.svg",
    "bytes": 534,
    "sha256": "8f86f05e844ea80ab1b5cc723b4ee72462e81a45b50675a48406b68cf5f20961",
    "geometry": {
      "viewBox": "0 0 112.9 136.4",
      "fill": "#27382f",
      "shapes": [
        {
          "tag": "path",
          "d": "M23.5,136.4h89.4v-23.5H23.5V136.4z M0,112.9h23.5V23.5H0V112.9z M23.5,23.5h89.4V0H23.5V23.5z"
        }
      ]
    }
  },
  {
    "id": "icon-svg-convert-icon-light-green",
    "family": "Icon",
    "label": "Icon",
    "colour": "Light Green",
    "format": "svg",
    "clearSpace": false,
    "source": "Icon/SVG/Convert_Icon_Light Green.svg",
    "href": "/brand/logos/icon-svg-convert-icon-light-green.svg",
    "bytes": 534,
    "sha256": "ab6e5375984e49f3b371785097dd46f6f8f7e8db07061a277279f7ea6f52a04f",
    "geometry": {
      "viewBox": "0 0 112.9 136.4",
      "fill": "#c9deb6",
      "shapes": [
        {
          "tag": "path",
          "d": "M23.5,136.4h89.4v-23.5H23.5V136.4z M0,112.9h23.5V23.5H0V112.9z M23.5,23.5h89.4V0H23.5V23.5z"
        }
      ]
    }
  },
  {
    "id": "icon-svg-convert-icon-white",
    "family": "Icon",
    "label": "Icon",
    "colour": "White",
    "format": "svg",
    "clearSpace": false,
    "source": "Icon/SVG/Convert_Icon_White.svg",
    "href": "/brand/logos/icon-svg-convert-icon-white.svg",
    "bytes": 534,
    "sha256": "bd1bfa6e14f5c7c39bdfa7f5e14e1b104c39c642bcf9197df8a7bdce5e9b5e7a",
    "geometry": {
      "viewBox": "0 0 112.9 136.4",
      "fill": "#faf9f7",
      "shapes": [
        {
          "tag": "path",
          "d": "M23.5,136.4h89.4v-23.5H23.5V136.4z M0,112.9h23.5V23.5H0V112.9z M23.5,23.5h89.4V0H23.5V23.5z"
        }
      ]
    }
  },
  {
    "id": "logo-jpeg-clear-space-convert-logo-clear-space-black",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "Black",
    "format": "jpg",
    "clearSpace": true,
    "source": "Logo/JPEG/Clear Space/Convert_Logo_Clear Space_Black.jpg",
    "href": "/brand/logos/logo-jpeg-clear-space-convert-logo-clear-space-black.jpg",
    "bytes": 221722,
    "sha256": "679390feb3b617d49edb6b6555040be4524458f79667e91d89e6198ed9cdd21d"
  },
  {
    "id": "logo-jpeg-clear-space-convert-logo-clear-space-dark-green",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "Dark Green",
    "format": "jpg",
    "clearSpace": true,
    "source": "Logo/JPEG/Clear Space/Convert_Logo_Clear Space_Dark Green.jpg",
    "href": "/brand/logos/logo-jpeg-clear-space-convert-logo-clear-space-dark-green.jpg",
    "bytes": 257539,
    "sha256": "eb569d85b92d730c584160583969b5015b7eee104dcef73df130adff1832c004"
  },
  {
    "id": "logo-jpeg-clear-space-convert-logo-clear-space-light-green",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "Light Green",
    "format": "jpg",
    "clearSpace": true,
    "source": "Logo/JPEG/Clear Space/Convert_Logo_Clear Space_Light Green.jpg",
    "href": "/brand/logos/logo-jpeg-clear-space-convert-logo-clear-space-light-green.jpg",
    "bytes": 255579,
    "sha256": "292f863eba36609d4c2dcc1fa367b416e2e50b8096049eb405e39a6dfa5a12a3"
  },
  {
    "id": "logo-jpeg-clear-space-convert-logo-clear-space-white",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "White",
    "format": "jpg",
    "clearSpace": true,
    "source": "Logo/JPEG/Clear Space/Convert_Logo_Clear Space_White.jpg",
    "href": "/brand/logos/logo-jpeg-clear-space-convert-logo-clear-space-white.jpg",
    "bytes": 152449,
    "sha256": "606e5cae7f7d943af96e9150f00727f9e03bfed7ac364f53a0b55a9a9eb40dd2"
  },
  {
    "id": "logo-jpeg-convert-logo-black",
    "family": "Logo",
    "label": "Logo",
    "colour": "Black",
    "format": "jpg",
    "clearSpace": false,
    "source": "Logo/JPEG/Convert_Logo_Black.jpg",
    "href": "/brand/logos/logo-jpeg-convert-logo-black.jpg",
    "bytes": 140347,
    "sha256": "7d45f64d583d998ad6b032eadddcbaf9e53cdbac50d1e77a7aac15fd8465b237"
  },
  {
    "id": "logo-jpeg-convert-logo-dark-green",
    "family": "Logo",
    "label": "Logo",
    "colour": "Dark Green",
    "format": "jpg",
    "clearSpace": false,
    "source": "Logo/JPEG/Convert_Logo_Dark Green.jpg",
    "href": "/brand/logos/logo-jpeg-convert-logo-dark-green.jpg",
    "bytes": 173792,
    "sha256": "dee1f0cd194aeb9c89344cc01db484643e9393bf443aff648aa48480527b4568"
  },
  {
    "id": "logo-jpeg-convert-logo-light-green",
    "family": "Logo",
    "label": "Logo",
    "colour": "Light Green",
    "format": "jpg",
    "clearSpace": false,
    "source": "Logo/JPEG/Convert_Logo_Light Green.jpg",
    "href": "/brand/logos/logo-jpeg-convert-logo-light-green.jpg",
    "bytes": 176307,
    "sha256": "77fca4f394cfdb7692c5bb39caabaed0c6c7e8f9dff85819d7aab46c0d668bd9"
  },
  {
    "id": "logo-jpeg-convert-logo-white",
    "family": "Logo",
    "label": "Logo",
    "colour": "White",
    "format": "jpg",
    "clearSpace": false,
    "source": "Logo/JPEG/Convert_Logo_White.jpg",
    "href": "/brand/logos/logo-jpeg-convert-logo-white.jpg",
    "bytes": 74205,
    "sha256": "2a8454f4060443692c798e5e67863a3b94507a76012b56ba089e12b87f4f1fe0"
  },
  {
    "id": "logo-png-clear-space-convert-logo-clear-space-black",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "Black",
    "format": "png",
    "clearSpace": true,
    "source": "Logo/PNG/Clear Space/Convert_Logo_Clear Space_Black.png",
    "href": "/brand/logos/logo-png-clear-space-convert-logo-clear-space-black.png",
    "bytes": 76734,
    "sha256": "9f15a9c9b4477a5d5c3db7aad9e79b69608a7793b9ab875b86d973887b3c4d61"
  },
  {
    "id": "logo-png-clear-space-convert-logo-clear-space-dark-green",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "Dark Green",
    "format": "png",
    "clearSpace": true,
    "source": "Logo/PNG/Clear Space/Convert_Logo_Clear Space_Dark Green.png",
    "href": "/brand/logos/logo-png-clear-space-convert-logo-clear-space-dark-green.png",
    "bytes": 77550,
    "sha256": "f00fabab16fc2ff30da57bbf90379688b617992ca36098c890b21390a8cd5167"
  },
  {
    "id": "logo-png-clear-space-convert-logo-clear-space-light-green",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "Light Green",
    "format": "png",
    "clearSpace": true,
    "source": "Logo/PNG/Clear Space/Convert_Logo_Clear Space_Light Green.png",
    "href": "/brand/logos/logo-png-clear-space-convert-logo-clear-space-light-green.png",
    "bytes": 78092,
    "sha256": "f287b165236c72c46ecc7507fc9c8a446f567e7f905c9130fdfe57621e406ea2"
  },
  {
    "id": "logo-png-clear-space-convert-logo-clear-space-white",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "White",
    "format": "png",
    "clearSpace": true,
    "source": "Logo/PNG/Clear Space/Convert_Logo_Clear Space_White.png",
    "href": "/brand/logos/logo-png-clear-space-convert-logo-clear-space-white.png",
    "bytes": 77692,
    "sha256": "c0785c44e86ec8a9313f3546ee45de72013b8298656ee2a67e10d17b5497e801"
  },
  {
    "id": "logo-png-convert-logo-black",
    "family": "Logo",
    "label": "Logo",
    "colour": "Black",
    "format": "png",
    "clearSpace": false,
    "source": "Logo/PNG/Convert_Logo_Black.png",
    "href": "/brand/logos/logo-png-convert-logo-black.png",
    "bytes": 47395,
    "sha256": "8c5efc3441bcfb4e168df4c2aa925c2165b3b82b3eee13842a72d8edef7e2d45"
  },
  {
    "id": "logo-png-convert-logo-dark-green",
    "family": "Logo",
    "label": "Logo",
    "colour": "Dark Green",
    "format": "png",
    "clearSpace": false,
    "source": "Logo/PNG/Convert_Logo_Dark Green.png",
    "href": "/brand/logos/logo-png-convert-logo-dark-green.png",
    "bytes": 48114,
    "sha256": "baa8b98b49ed0412ceed4a21516de410e85b64c83cffcb715d1abc5a691f4f78"
  },
  {
    "id": "logo-png-convert-logo-light-green",
    "family": "Logo",
    "label": "Logo",
    "colour": "Light Green",
    "format": "png",
    "clearSpace": false,
    "source": "Logo/PNG/Convert_Logo_Light Green.png",
    "href": "/brand/logos/logo-png-convert-logo-light-green.png",
    "bytes": 48327,
    "sha256": "2f48d28934b186a21e01dffb600b348c7ba32cd01329fb6acdd2f7c7aaaa3af1"
  },
  {
    "id": "logo-png-convert-logo-white",
    "family": "Logo",
    "label": "Logo",
    "colour": "White",
    "format": "png",
    "clearSpace": false,
    "source": "Logo/PNG/Convert_Logo_White.png",
    "href": "/brand/logos/logo-png-convert-logo-white.png",
    "bytes": 48209,
    "sha256": "580360bbd52172372129d0c9ae930ae03cd9e3080c9576cc0d4b921ca13b1786"
  },
  {
    "id": "logo-svg-clear-space-convert-logo-clear-space-black",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "Black",
    "format": "svg",
    "clearSpace": true,
    "source": "Logo/SVG/Clear Space/Convert_Logo_Clear Space_Black.svg",
    "href": "/brand/logos/logo-svg-clear-space-convert-logo-clear-space-black.svg",
    "bytes": 1384,
    "sha256": "527a3ad8828686ddc7d3644406095d119674f2a68c41c10f83be67285a3bc7fb",
    "geometry": {
      "viewBox": "0 0 1198 414.8",
      "fill": "#171717",
      "shapes": [
        {
          "tag": "path",
          "d": "M498.4,140.4l36.5,125h1.2v-125h35.3V275h-69.2l-36.5-125h-1.2v125h-35.3V140.4H498.4z M708.9,140.4L676.2,275\n\th-67.3l-32.7-134.6h38.5l27.9,120.2l27.9-120.2L708.9,140.4L708.9,140.4z M817.8,140.4v26.9h-65.4v25h57.7v26.9h-57.7v28.9h65.4V275\n\tH713.9V140.4H817.8z M891.8,201c11.5,0,17.3-7.5,17.3-17.3s-5.7-17.3-17.3-17.3H863V201H891.8z M893.8,140.4\n\tc38.5,0,53.8,21.1,53.8,44.2c0,17.1-6.9,30.6-23.8,37.5l27.7,53.1h-40.4L889,226.9h-26V275h-38.5V140.4H893.8z M950.3,140.4v30.8\n\tH986V275h38.4V171.2h35.7v-30.8H950.3z M207.2,166.8c-21.7,0-30.8,12.1-30.8,41.1c0,28.6,9,41,30.8,41c16.2,0,24-6,26.9-20.6h38.5\n\tc-7.5,34-27.1,48.6-65.4,48.6c-49.8,0-69.2-20.8-69.2-69c0-48.4,19.4-69.2,69.2-69.2c40.8,0,60.6,14.6,65.4,48.6h-38.5\n\tC231.2,172.7,223.4,166.8,207.2,166.8 M350.2,248.7c21.7,0,32.7-12.3,32.7-41s-11-41-32.7-41s-32.7,12.3-32.7,41\n\tS328.5,248.7,350.2,248.7 M350.2,139c49.8,0,71.1,20.6,71.1,68.8s-21.3,68.8-71.1,68.8S279,256,279,207.8S300.4,139,350.2,139"
        }
      ]
    }
  },
  {
    "id": "logo-svg-clear-space-convert-logo-clear-space-dark-green",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "Dark Green",
    "format": "svg",
    "clearSpace": true,
    "source": "Logo/SVG/Clear Space/Convert_Logo_Clear Space_Dark Green.svg",
    "href": "/brand/logos/logo-svg-clear-space-convert-logo-clear-space-dark-green.svg",
    "bytes": 1378,
    "sha256": "e4aa3bc82bd67834a1c652d763723bf1976f726061f03736b2d87ee0749d4ec1",
    "geometry": {
      "viewBox": "0 0 1198 414.8",
      "fill": "#27382f",
      "shapes": [
        {
          "tag": "path",
          "d": "M498.4,140.4l36.5,125h1.2v-125h35.3V275h-69.2l-36.5-125h-1.2v125h-35.3V140.4H498.4z M708.9,140.4L676.2,275\n\th-67.3l-32.7-134.6h38.5l27.9,120.2l27.9-120.2H708.9z M817.8,140.4v26.9h-65.4v25h57.7v26.9h-57.7v28.9h65.4V275H713.9V140.4H817.8\n\tz M891.8,201c11.5,0,17.3-7.5,17.3-17.3c0-9.8-5.7-17.3-17.3-17.3H863V201H891.8z M893.8,140.4c38.5,0,53.8,21.1,53.8,44.2\n\tc0,17.1-6.9,30.6-23.8,37.5l27.7,53.1h-40.4L889,226.9h-26V275h-38.5V140.4H893.8z M950.3,140.4v30.8H986V275h38.4V171.2h35.7v-30.8\n\tH950.3z M207.2,166.8c-21.7,0-30.8,12.1-30.8,41.1c0,28.6,9,41,30.8,41c16.2,0,24-6,26.9-20.6h38.5c-7.5,34-27.1,48.6-65.4,48.6\n\tc-49.8,0-69.2-20.8-69.2-69c0-48.4,19.4-69.2,69.2-69.2c40.8,0,60.6,14.6,65.4,48.6h-38.5C231.2,172.7,223.4,166.8,207.2,166.8\n\t M350.2,248.7c21.7,0,32.7-12.3,32.7-41s-11-41-32.7-41c-21.7,0-32.7,12.3-32.7,41S328.5,248.7,350.2,248.7 M350.2,139\n\tc49.8,0,71.1,20.6,71.1,68.8s-21.3,68.8-71.1,68.8S279,256,279,207.8S300.4,139,350.2,139"
        }
      ]
    }
  },
  {
    "id": "logo-svg-clear-space-convert-logo-clear-space-light-green",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "Light Green",
    "format": "svg",
    "clearSpace": true,
    "source": "Logo/SVG/Clear Space/Convert_Logo_Clear Space_Light Green.svg",
    "href": "/brand/logos/logo-svg-clear-space-convert-logo-clear-space-light-green.svg",
    "bytes": 1404,
    "sha256": "b43e1005e7eac911b142f34ba16a1c8a9a8f713e9cfec2be2b5b3b7085e4b18c",
    "geometry": {
      "viewBox": "0 0 1198 414.8",
      "fill": "#c9deb6",
      "shapes": [
        {
          "tag": "path",
          "d": "M498.3,140.1l36.5,125h1.2v-125h35.3v134.6h-69.2l-36.5-125h-1.2v125h-35.3V140.1H498.3z M708.8,140.1\n\tl-32.7,134.6h-67.3l-32.7-134.6h38.5l27.9,120.2l27.9-120.2H708.8z M817.8,140.1V167h-65.4v25H810v26.9h-57.7v28.9h65.4v26.9H713.8\n\tV140.1H817.8z M891.8,200.7c11.5,0,17.3-7.5,17.3-17.3c0-9.8-5.7-17.3-17.3-17.3h-28.8v34.6H891.8z M893.8,140.1\n\tc38.5,0,53.8,21.1,53.8,44.2c0,17.1-6.9,30.6-23.8,37.5l27.7,53.1H911l-22.1-48.3h-26v48.1h-38.5V140.1H893.8z M950.2,140.1v30.8\n\th35.7v103.8h38.4V170.9h35.7v-30.8H950.2z M207.1,166.5c-21.7,0-30.8,12.1-30.8,41.1c0,28.6,9,41,30.8,41c16.2,0,24-6,26.9-20.6\n\th38.5c-7.5,34-27.1,48.6-65.4,48.6c-49.8,0-69.2-20.8-69.2-69c0-48.4,19.4-69.2,69.2-69.2c40.8,0,60.6,14.6,65.4,48.6H234\n\tC231.1,172.4,223.3,166.5,207.1,166.5 M350.1,248.4c21.7,0,32.7-12.3,32.7-41c0-28.7-11-41-32.7-41c-21.7,0-32.7,12.3-32.7,41\n\tS328.4,248.4,350.1,248.4 M350.1,138.7c49.8,0,71.1,20.6,71.1,68.8s-21.3,68.8-71.1,68.8s-71.2-20.6-71.2-68.8\n\tS300.3,138.7,350.1,138.7"
        }
      ]
    }
  },
  {
    "id": "logo-svg-clear-space-convert-logo-clear-space-white",
    "family": "Logo",
    "label": "Logo, clear space",
    "colour": "White",
    "format": "svg",
    "clearSpace": true,
    "source": "Logo/SVG/Clear Space/Convert_Logo_Clear Space_White.svg",
    "href": "/brand/logos/logo-svg-clear-space-convert-logo-clear-space-white.svg",
    "bytes": 1378,
    "sha256": "cfaba1faa23683a0909819c7ed469f9f843e3eedfe72719c982d44affba80e35",
    "geometry": {
      "viewBox": "0 0 1198 414.8",
      "fill": "#faf9f7",
      "shapes": [
        {
          "tag": "path",
          "d": "M498.4,140.4l36.5,125h1.2v-125h35.3V275h-69.2l-36.5-125h-1.2v125h-35.3V140.4H498.4z M708.9,140.4L676.2,275\n\th-67.3l-32.7-134.6h38.5l27.9,120.2l27.9-120.2H708.9z M817.8,140.4v26.9h-65.4v25h57.7v26.9h-57.7v28.9h65.4V275H713.9V140.4H817.8\n\tz M891.8,201c11.5,0,17.3-7.5,17.3-17.3c0-9.8-5.7-17.3-17.3-17.3H863V201H891.8z M893.8,140.4c38.5,0,53.8,21.1,53.8,44.2\n\tc0,17.1-6.9,30.6-23.8,37.5l27.7,53.1h-40.4L889,226.9h-26V275h-38.5V140.4H893.8z M950.3,140.4v30.8H986V275h38.4V171.2h35.7v-30.8\n\tH950.3z M207.2,166.8c-21.7,0-30.8,12.1-30.8,41.1c0,28.6,9,41,30.8,41c16.2,0,24-6,26.9-20.6h38.5c-7.5,34-27.1,48.6-65.4,48.6\n\tc-49.8,0-69.2-20.8-69.2-69c0-48.4,19.4-69.2,69.2-69.2c40.8,0,60.6,14.6,65.4,48.6h-38.5C231.2,172.7,223.4,166.8,207.2,166.8\n\t M350.2,248.7c21.7,0,32.7-12.3,32.7-41s-11-41-32.7-41c-21.7,0-32.7,12.3-32.7,41S328.5,248.7,350.2,248.7 M350.2,139\n\tc49.8,0,71.1,20.6,71.1,68.8s-21.3,68.8-71.1,68.8S279,256,279,207.8S300.4,139,350.2,139"
        }
      ]
    }
  },
  {
    "id": "logo-svg-convert-logo-black",
    "family": "Logo",
    "label": "Logo",
    "colour": "Black",
    "format": "svg",
    "clearSpace": false,
    "source": "Logo/SVG/Convert_Logo_Black.svg",
    "href": "/brand/logos/logo-svg-convert-logo-black.svg",
    "bytes": 1339,
    "sha256": "4dc3ddcd1ab6d3f3039b842342682786dc4714481f581ad98730ce2c98009dbc",
    "geometry": {
      "viewBox": "0 0 922.1 138.2",
      "fill": "#171717",
      "shapes": [
        {
          "tag": "path",
          "d": "M360.4,1.7l36.5,125h1.2V1.7h35.3v134.6h-69.2l-36.5-125h-1.2v125h-35.3V1.7H360.4z M570.9,1.7l-32.7,134.6\n\th-67.3L438.2,1.7h38.5l27.9,120.2L532.5,1.7H570.9z M679.8,1.7v26.9h-65.4v25h57.7v26.9h-57.7v28.9h65.4v26.9H575.9V1.7H679.8z\n\t M753.8,62.3c11.5,0,17.3-7.5,17.3-17.3s-5.7-17.3-17.3-17.3H725v34.6H753.8z M755.8,1.7c38.5,0,53.8,21.1,53.8,44.2\n\tc0,17.1-6.9,30.6-23.8,37.5l27.7,53.1h-40.4L751,88.2h-26v48.1h-38.5V1.7H755.8z M812.3,1.7v30.8H848v103.8h38.4V32.5h35.7V1.7\n\tH812.3z M69.2,28.1c-21.7,0-30.8,12.1-30.8,41.1c0,28.6,9,41,30.8,41c16.2,0,24-6,26.9-20.6h38.5c-7.5,34-27.1,48.6-65.4,48.6\n\tc-49.8,0-69.2-20.8-69.2-69C0,20.8,19.4,0,69.2,0c40.8,0,60.6,14.6,65.4,48.6H96.1C93.2,34,85.4,28.1,69.2,28.1 M212.2,110\n\tc21.7,0,32.7-12.3,32.7-41s-11-41-32.7-41c-21.7,0-32.7,12.3-32.7,41S190.5,110,212.2,110 M212.2,0.3c49.8,0,71.1,20.6,71.1,68.8\n\ts-21.3,68.8-71.1,68.8S141,117.3,141,69.1S162.4,0.3,212.2,0.3"
        }
      ]
    }
  },
  {
    "id": "logo-svg-convert-logo-dark-green",
    "family": "Logo",
    "label": "Logo",
    "colour": "Dark Green",
    "format": "svg",
    "clearSpace": false,
    "source": "Logo/SVG/Convert_Logo_Dark Green.svg",
    "href": "/brand/logos/logo-svg-convert-logo-dark-green.svg",
    "bytes": 1332,
    "sha256": "74dda36c1a2e86e318e33bc096809bdc1e6b306159381e00f6344ff23bf4a86a",
    "geometry": {
      "viewBox": "0 0 922.1 138.2",
      "fill": "#27382f",
      "shapes": [
        {
          "tag": "path",
          "d": "M360.4,1.7l36.5,125h1.2V1.7h35.3v134.6h-69.2l-36.5-125h-1.2v125h-35.3V1.7H360.4z M570.9,1.7l-32.7,134.6\n\th-67.3L438.2,1.7h38.5l27.9,120.2L532.5,1.7H570.9z M679.8,1.7v26.9h-65.4v25h57.7v26.9h-57.7v28.9h65.4v26.9H575.9V1.7H679.8z\n\t M753.8,62.3c11.5,0,17.3-7.5,17.3-17.3s-5.7-17.3-17.3-17.3H725v34.6H753.8z M755.8,1.7c38.5,0,53.8,21.1,53.8,44.2\n\tc0,17.1-6.9,30.6-23.8,37.5l27.7,53.1h-40.4L751,88.2h-26v48.1h-38.5V1.7H755.8z M812.3,1.7v30.8H848v103.8h38.4V32.5h35.7V1.7\n\tH812.3z M69.2,28.1c-21.7,0-30.8,12.1-30.8,41.1c0,28.6,9,41,30.8,41c16.2,0,24-6,26.9-20.6h38.5c-7.5,34-27.1,48.6-65.4,48.6\n\tc-49.8,0-69.2-20.8-69.2-69C0,20.8,19.4,0,69.2,0c40.8,0,60.6,14.6,65.4,48.6H96.1C93.2,34,85.4,28.1,69.2,28.1 M212.2,110\n\tc21.7,0,32.7-12.3,32.7-41s-11-41-32.7-41s-32.7,12.3-32.7,41S190.5,110,212.2,110 M212.2,0.3c49.8,0,71.1,20.6,71.1,68.8\n\ts-21.3,68.8-71.1,68.8S141,117.3,141,69.1S162.4,0.3,212.2,0.3"
        }
      ]
    }
  },
  {
    "id": "logo-svg-convert-logo-light-green",
    "family": "Logo",
    "label": "Logo",
    "colour": "Light Green",
    "format": "svg",
    "clearSpace": false,
    "source": "Logo/SVG/Convert_Logo_Light Green.svg",
    "href": "/brand/logos/logo-svg-convert-logo-light-green.svg",
    "bytes": 1332,
    "sha256": "2393cdcb6cc40d3efb9ab3f2b3c5c16c6cc0a8352f7dab35c1af41d698ff710c",
    "geometry": {
      "viewBox": "0 0 922.1 138.2",
      "fill": "#c9deb6",
      "shapes": [
        {
          "tag": "path",
          "d": "M360.4,1.7l36.5,125h1.2V1.7h35.3v134.6h-69.2l-36.5-125h-1.2v125h-35.3V1.7H360.4z M570.9,1.7l-32.7,134.6\n\th-67.3L438.2,1.7h38.5l27.9,120.2L532.5,1.7H570.9z M679.8,1.7v26.9h-65.4v25h57.7v26.9h-57.7v28.9h65.4v26.9H575.9V1.7H679.8z\n\t M753.8,62.3c11.5,0,17.3-7.5,17.3-17.3s-5.7-17.3-17.3-17.3H725v34.6H753.8z M755.8,1.7c38.5,0,53.8,21.1,53.8,44.2\n\tc0,17.1-6.9,30.6-23.8,37.5l27.7,53.1h-40.4L751,88.2h-26v48.1h-38.5V1.7H755.8z M812.3,1.7v30.8H848v103.8h38.4V32.5h35.7V1.7\n\tH812.3z M69.2,28.1c-21.7,0-30.8,12.1-30.8,41.1c0,28.6,9,41,30.8,41c16.2,0,24-6,26.9-20.6h38.5c-7.5,34-27.1,48.6-65.4,48.6\n\tc-49.8,0-69.2-20.8-69.2-69C0,20.8,19.4,0,69.2,0c40.8,0,60.6,14.6,65.4,48.6H96.1C93.2,34,85.4,28.1,69.2,28.1 M212.2,110\n\tc21.7,0,32.7-12.3,32.7-41s-11-41-32.7-41s-32.7,12.3-32.7,41S190.5,110,212.2,110 M212.2,0.3c49.8,0,71.1,20.6,71.1,68.8\n\ts-21.3,68.8-71.1,68.8S141,117.3,141,69.1S162.4,0.3,212.2,0.3"
        }
      ]
    }
  },
  {
    "id": "logo-svg-convert-logo-white",
    "family": "Logo",
    "label": "Logo",
    "colour": "White",
    "format": "svg",
    "clearSpace": false,
    "source": "Logo/SVG/Convert_Logo_White.svg",
    "href": "/brand/logos/logo-svg-convert-logo-white.svg",
    "bytes": 1339,
    "sha256": "ee43a7293f8d66577997283dc7b22320eb556cdfbe58c5521ecd298c11d97e86",
    "geometry": {
      "viewBox": "0 0 922.1 138.2",
      "fill": "#faf9f7",
      "shapes": [
        {
          "tag": "path",
          "d": "M360.4,1.7l36.5,125h1.2V1.7h35.3v134.6h-69.2l-36.5-125h-1.2v125h-35.3V1.7H360.4z M570.9,1.7l-32.7,134.6\n\th-67.3L438.2,1.7h38.5l27.9,120.2L532.5,1.7H570.9z M679.8,1.7v26.9h-65.4v25h57.7v26.9h-57.7v28.9h65.4v26.9H575.9V1.7H679.8z\n\t M753.8,62.3c11.5,0,17.3-7.5,17.3-17.3s-5.7-17.3-17.3-17.3H725v34.6H753.8z M755.8,1.7c38.5,0,53.8,21.1,53.8,44.2\n\tc0,17.1-6.9,30.6-23.8,37.5l27.7,53.1h-40.4L751,88.2h-26v48.1h-38.5V1.7H755.8z M812.3,1.7v30.8H848v103.8h38.4V32.5h35.7V1.7\n\tH812.3z M69.2,28.1c-21.7,0-30.8,12.1-30.8,41.1c0,28.6,9,41,30.8,41c16.2,0,24-6,26.9-20.6h38.5c-7.5,34-27.1,48.6-65.4,48.6\n\tc-49.8,0-69.2-20.8-69.2-69C0,20.8,19.4,0,69.2,0c40.8,0,60.6,14.6,65.4,48.6H96.1C93.2,34,85.4,28.1,69.2,28.1 M212.2,110\n\tc21.7,0,32.7-12.3,32.7-41s-11-41-32.7-41c-21.7,0-32.7,12.3-32.7,41S190.5,110,212.2,110 M212.2,0.3c49.8,0,71.1,20.6,71.1,68.8\n\ts-21.3,68.8-71.1,68.8S141,117.3,141,69.1S162.4,0.3,212.2,0.3"
        }
      ]
    }
  },
  {
    "id": "profile-icons-cdpi-round-darkgreen",
    "family": "Profile icon",
    "label": "CDPI Round DarkGreen",
    "colour": null,
    "format": "png",
    "clearSpace": false,
    "source": "Profile Icons/CDPI_Round_DarkGreen.png",
    "href": "/brand/logos/profile-icons-cdpi-round-darkgreen.png",
    "bytes": 9243,
    "sha256": "d2b18bd3b13312d94d98c953d39646c00829a3e1502bd026ca5d0ab70e938358"
  },
  {
    "id": "profile-icons-cdpi-round-darkgreen-lightgreen",
    "family": "Profile icon",
    "label": "CDPI Round DarkGreen LightGreen",
    "colour": null,
    "format": "png",
    "clearSpace": false,
    "source": "Profile Icons/CDPI_Round_DarkGreen_LightGreen.png",
    "href": "/brand/logos/profile-icons-cdpi-round-darkgreen-lightgreen.png",
    "bytes": 9212,
    "sha256": "589aadabc83673353cf2601de454ed5ad3bbb200c0b433fc5ec201938a5e4277"
  },
  {
    "id": "profile-icons-cdpi-round-lightgreen",
    "family": "Profile icon",
    "label": "CDPI Round LightGreen",
    "colour": null,
    "format": "png",
    "clearSpace": false,
    "source": "Profile Icons/CDPI_Round_LightGreen.png",
    "href": "/brand/logos/profile-icons-cdpi-round-lightgreen.png",
    "bytes": 9161,
    "sha256": "9812860d1fb4cfc6c4218f856cdf5e42c149625a8b8a8c944ab5e937ae7b8c10"
  },
  {
    "id": "profile-icons-cd-icon-2",
    "family": "Profile icon",
    "label": "CD Icon 2",
    "colour": null,
    "format": "png",
    "clearSpace": false,
    "source": "Profile Icons/CD_Icon_2.png",
    "href": "/brand/logos/profile-icons-cd-icon-2.png",
    "bytes": 23401,
    "sha256": "1633dbe65afe7133f7cff5a33d5838b43a44c673c15e71c5bcdc0a746fbf4361"
  },
  {
    "id": "profile-icons-cd-icon-3",
    "family": "Profile icon",
    "label": "CD Icon 3",
    "colour": null,
    "format": "png",
    "clearSpace": false,
    "source": "Profile Icons/CD_Icon_3.png",
    "href": "/brand/logos/profile-icons-cd-icon-3.png",
    "bytes": 23411,
    "sha256": "972519ab63d7b624a8da21b2307317eec48187364ec7da06bb79cc239f4f8b19"
  },
  {
    "id": "profile-icons-cd-icon-4",
    "family": "Profile icon",
    "label": "CD Icon 4",
    "colour": null,
    "format": "png",
    "clearSpace": false,
    "source": "Profile Icons/CD_Icon_4.png",
    "href": "/brand/logos/profile-icons-cd-icon-4.png",
    "bytes": 23412,
    "sha256": "a53244c23fc87a1c25a2c0ab8ec4e6002d54d53ff68c44bd72ba98536d326996"
  },
  {
    "id": "profile-icons-cd-profile-icon",
    "family": "Profile icon",
    "label": "CD Profile Icon",
    "colour": null,
    "format": "jpg",
    "clearSpace": false,
    "source": "Profile Icons/CD_Profile_Icon.jpg",
    "href": "/brand/logos/profile-icons-cd-profile-icon.jpg",
    "bytes": 163949,
    "sha256": "b25587113c9a2fc02bae2f46a188ad5193e045da16704e7f548a585fc6401cc2"
  },
  {
    "id": "profile-icons-cd-profile-logo-icon",
    "family": "Profile icon",
    "label": "CD Profile Logo Icon",
    "colour": null,
    "format": "jpg",
    "clearSpace": false,
    "source": "Profile Icons/CD_Profile_Logo_Icon.jpg",
    "href": "/brand/logos/profile-icons-cd-profile-logo-icon.jpg",
    "bytes": 210267,
    "sha256": "8d409a349fcc1ef442e92c6901952fcdc03bc3788f8e0c24f01c5228d078a6d5"
  },
  {
    "id": "straight-jpeg-clear-space-convert-logo-straight-black-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "Black",
    "format": "jpg",
    "clearSpace": true,
    "source": "Straight/JPEG/Clear Space/Convert_Logo_Straight_Black_Clear Space.jpg",
    "href": "/brand/logos/straight-jpeg-clear-space-convert-logo-straight-black-clear-space.jpg",
    "bytes": 216117,
    "sha256": "d961bc7c003e6c81b8b233ef5448ee1b4cf590e79b4f7552cdf95688c0ff5f4c"
  },
  {
    "id": "straight-jpeg-clear-space-convert-logo-straight-dark-green-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "Dark Green",
    "format": "jpg",
    "clearSpace": true,
    "source": "Straight/JPEG/Clear Space/Convert_Logo_Straight_Dark Green_Clear Space.jpg",
    "href": "/brand/logos/straight-jpeg-clear-space-convert-logo-straight-dark-green-clear-space.jpg",
    "bytes": 238585,
    "sha256": "51a97bfa84b03d805b6d7c2746433043536eba35e937821f040c31ba5ec8d268"
  },
  {
    "id": "straight-jpeg-clear-space-convert-logo-straight-light-green-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "Light Green",
    "format": "jpg",
    "clearSpace": true,
    "source": "Straight/JPEG/Clear Space/Convert_Logo_Straight_Light Green_Clear Space.jpg",
    "href": "/brand/logos/straight-jpeg-clear-space-convert-logo-straight-light-green-clear-space.jpg",
    "bytes": 225668,
    "sha256": "c779114f4ecea28e9fc4c1143f15f0f87e43db180a8fa0b9e55206b728396a2e"
  },
  {
    "id": "straight-jpeg-clear-space-convert-logo-straight-white-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "White",
    "format": "jpg",
    "clearSpace": true,
    "source": "Straight/JPEG/Clear Space/Convert_Logo_Straight_White_Clear Space.jpg",
    "href": "/brand/logos/straight-jpeg-clear-space-convert-logo-straight-white-clear-space.jpg",
    "bytes": 157669,
    "sha256": "749cbfb9a113491ba2154c7539a96b83a19d09c32321085b69714fb1b6346d2c"
  },
  {
    "id": "straight-jpeg-convert-logo-straight-black",
    "family": "Straight",
    "label": "Straight",
    "colour": "Black",
    "format": "jpg",
    "clearSpace": false,
    "source": "Straight/JPEG/Convert_Logo_Straight_Black.jpg",
    "href": "/brand/logos/straight-jpeg-convert-logo-straight-black.jpg",
    "bytes": 163231,
    "sha256": "47fff335d5d94531bb7a5d4685a74a9f7266d42680580741416979cbd9b427dd"
  },
  {
    "id": "straight-jpeg-convert-logo-straight-dark-green",
    "family": "Straight",
    "label": "Straight",
    "colour": "Dark Green",
    "format": "jpg",
    "clearSpace": false,
    "source": "Straight/JPEG/Convert_Logo_Straight_Dark Green.jpg",
    "href": "/brand/logos/straight-jpeg-convert-logo-straight-dark-green.jpg",
    "bytes": 185371,
    "sha256": "02d1229fc489bab5df4f3ba71fe0e9171bc1373d1c388de560742933e8cf376a"
  },
  {
    "id": "straight-jpeg-convert-logo-straight-light-green",
    "family": "Straight",
    "label": "Straight",
    "colour": "Light Green",
    "format": "jpg",
    "clearSpace": false,
    "source": "Straight/JPEG/Convert_Logo_Straight_Light Green.jpg",
    "href": "/brand/logos/straight-jpeg-convert-logo-straight-light-green.jpg",
    "bytes": 172698,
    "sha256": "c81166bc93f136746b015f48dcf7162fb3554a32abf65d03c121cb9fc9dbe4c7"
  },
  {
    "id": "straight-jpeg-convert-logo-straight-white",
    "family": "Straight",
    "label": "Straight",
    "colour": "White",
    "format": "jpg",
    "clearSpace": false,
    "source": "Straight/JPEG/Convert_Logo_Straight_White.jpg",
    "href": "/brand/logos/straight-jpeg-convert-logo-straight-white.jpg",
    "bytes": 105372,
    "sha256": "586cbec6ef6b8c469a5643cd6b453adfde1c89e09d2dec0c025c2f514a13833b"
  },
  {
    "id": "straight-png-clear-space-convert-logo-straight-black-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "Black",
    "format": "png",
    "clearSpace": true,
    "source": "Straight/PNG/Clear Space/Convert_Logo_Straight_Black_Clear Space.png",
    "href": "/brand/logos/straight-png-clear-space-convert-logo-straight-black-clear-space.png",
    "bytes": 74894,
    "sha256": "14c965fe9cd177c8406d8d36b7800f035742757840c54c897439e76ccf2c258c"
  },
  {
    "id": "straight-png-clear-space-convert-logo-straight-dark-green-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "Dark Green",
    "format": "png",
    "clearSpace": true,
    "source": "Straight/PNG/Clear Space/Convert_Logo_Straight_Dark Green_Clear Space.png",
    "href": "/brand/logos/straight-png-clear-space-convert-logo-straight-dark-green-clear-space.png",
    "bytes": 75776,
    "sha256": "e00ce4e7ebc1e175fba140d3d86372bf4b661d28adfc5a2e81e8525a7d72d1fe"
  },
  {
    "id": "straight-png-clear-space-convert-logo-straight-light-green-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "Light Green",
    "format": "png",
    "clearSpace": true,
    "source": "Straight/PNG/Clear Space/Convert_Logo_Straight_Light Green_Clear Space.png",
    "href": "/brand/logos/straight-png-clear-space-convert-logo-straight-light-green-clear-space.png",
    "bytes": 75962,
    "sha256": "bb330d0b39f2c39a8bbfeb95b199bb28efcf1cfe2cf770bbd5a6cab52bb23464"
  },
  {
    "id": "straight-png-clear-space-convert-logo-straight-white-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "White",
    "format": "png",
    "clearSpace": true,
    "source": "Straight/PNG/Clear Space/Convert_Logo_Straight_White_Clear Space.png",
    "href": "/brand/logos/straight-png-clear-space-convert-logo-straight-white-clear-space.png",
    "bytes": 75902,
    "sha256": "cf3925600e6ce32c712e953959ba10f92a7d0c9d223d6ae97d61af4d77fe7f29"
  },
  {
    "id": "straight-png-convert-logo-straight-black",
    "family": "Straight",
    "label": "Straight",
    "colour": "Black",
    "format": "png",
    "clearSpace": false,
    "source": "Straight/PNG/Convert_Logo_Straight_Black.png",
    "href": "/brand/logos/straight-png-convert-logo-straight-black.png",
    "bytes": 52899,
    "sha256": "94709a6b6d807919e1efde553604a00113e70ec4e7690a5be92b66640aa93244"
  },
  {
    "id": "straight-png-convert-logo-straight-dark-green",
    "family": "Straight",
    "label": "Straight",
    "colour": "Dark Green",
    "format": "png",
    "clearSpace": false,
    "source": "Straight/PNG/Convert_Logo_Straight_Dark Green.png",
    "href": "/brand/logos/straight-png-convert-logo-straight-dark-green.png",
    "bytes": 53640,
    "sha256": "76d878649e8cea8f7b16fa362d37fc388624f3e983c62fe93d1cc4086dd4cfc8"
  },
  {
    "id": "straight-png-convert-logo-straight-light-green",
    "family": "Straight",
    "label": "Straight",
    "colour": "Light Green",
    "format": "png",
    "clearSpace": false,
    "source": "Straight/PNG/Convert_Logo_Straight_Light Green.png",
    "href": "/brand/logos/straight-png-convert-logo-straight-light-green.png",
    "bytes": 53824,
    "sha256": "1d5738133ce5ac439475190704a011c2d8b51e099e6882606bf9fdbf35f56272"
  },
  {
    "id": "straight-png-convert-logo-straight-white",
    "family": "Straight",
    "label": "Straight",
    "colour": "White",
    "format": "png",
    "clearSpace": false,
    "source": "Straight/PNG/Convert_Logo_Straight_White.png",
    "href": "/brand/logos/straight-png-convert-logo-straight-white.png",
    "bytes": 53864,
    "sha256": "c84e013512103e036cc93da7f038ffc5a43bdaa9533d2a4f5751ee645412c0b1"
  },
  {
    "id": "straight-svg-clear-space-convert-logo-straight-black-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "Black",
    "format": "svg",
    "clearSpace": true,
    "source": "Straight/SVG/Clear Space/Convert_Logo_Straight_Black_Clear Space.svg",
    "href": "/brand/logos/straight-svg-clear-space-convert-logo-straight-black-clear-space.svg",
    "bytes": 2009,
    "sha256": "1ca518a87d55aac7bccad270f13063ae3e6158bdb4d5abd407aa2d299ab440dd",
    "geometry": {
      "viewBox": "0 0 1348.68 372.53",
      "fill": "#171717",
      "shapes": [
        {
          "tag": "path",
          "d": "M430.58,147.94c-20.05,0-28.38,11.17-28.38,37.96s8.34,37.78,28.38,37.78c14.9,0,22.17-5.5,24.83-18.98h35.48c-6.92,31.4-25.01,44.88-60.31,44.88-45.94,0-63.86-19.16-63.86-63.68s17.92-63.86,63.86-63.86c37.6,0,55.88,13.48,60.31,44.88h-35.48c-2.66-13.48-9.93-18.98-24.83-18.98"
        },
        {
          "tag": "path",
          "d": "M562.48,224.77c20.04,0,30.16-11.35,30.16-37.78s-10.11-37.78-30.16-37.78-30.16,11.35-30.16,37.78,10.11,37.78,30.16,37.78M562.48,123.48c45.94,0,65.63,18.98,65.63,63.51s-19.69,63.5-65.63,63.5-65.63-18.98-65.63-63.5,19.69-63.51,65.63-63.51"
        },
        {
          "tag": "polygon",
          "points": "699.21 124 732.91 239.3 733.98 239.3 733.98 124 766.62 124 766.62 248.17 702.76 248.17 669.06 132.86 667.99 132.86 667.99 248.17 635.35 248.17 635.35 124 699.21 124"
        },
        {
          "tag": "polygon",
          "points": "893.45 124 863.29 248.17 801.21 248.17 771.05 124 806.53 124 832.25 234.86 857.97 124 893.45 124"
        },
        {
          "tag": "polygon",
          "points": "993.88 124 993.88 148.83 933.57 148.83 933.57 171.89 986.79 171.89 986.79 196.72 933.57 196.72 933.57 223.33 993.88 223.33 993.88 248.17 898.1 248.17 898.1 124 993.88 124"
        },
        {
          "tag": "path",
          "d": "M1062.23,180.76c10.64,0,15.96-6.92,15.96-15.96s-5.32-15.96-15.96-15.96h-26.61v31.93h26.61ZM1064,124c35.48,0,49.67,19.51,49.67,40.8,0,15.79-6.38,28.2-22,34.59l25.55,48.96h-37.25l-20.4-44.52h-23.95v44.35h-35.48v-124.17h63.86Z"
        },
        {
          "tag": "polygon",
          "points": "1116.13 124 1116.13 152.38 1149.05 152.38 1149.05 248.17 1184.53 248.17 1184.53 152.38 1217.45 152.38 1217.45 124 1116.13 124"
        },
        {
          "tag": "rect",
          "x": "131.22",
          "y": "124.11",
          "width": "32.68",
          "height": "124.32"
        },
        {
          "tag": "rect",
          "x": "163.91",
          "y": "91.43",
          "width": "124.32",
          "height": "32.68"
        },
        {
          "tag": "rect",
          "x": "163.91",
          "y": "248.43",
          "width": "124.32",
          "height": "32.68"
        }
      ]
    }
  },
  {
    "id": "straight-svg-clear-space-convert-logo-straight-dark-green-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "Dark Green",
    "format": "svg",
    "clearSpace": true,
    "source": "Straight/SVG/Clear Space/Convert_Logo_Straight_Dark Green_Clear Space.svg",
    "href": "/brand/logos/straight-svg-clear-space-convert-logo-straight-dark-green-clear-space.svg",
    "bytes": 2009,
    "sha256": "fa1df871447d061f50edf0b0b9791b562ea5536705f0e2d9ed66b582e79dc14c",
    "geometry": {
      "viewBox": "0 0 1348.68 372.53",
      "fill": "#27382f",
      "shapes": [
        {
          "tag": "path",
          "d": "M430.58,147.94c-20.05,0-28.38,11.17-28.38,37.96s8.34,37.78,28.38,37.78c14.9,0,22.17-5.5,24.83-18.98h35.48c-6.92,31.4-25.01,44.88-60.31,44.88-45.94,0-63.86-19.16-63.86-63.68s17.92-63.86,63.86-63.86c37.6,0,55.88,13.48,60.31,44.88h-35.48c-2.66-13.48-9.93-18.98-24.83-18.98"
        },
        {
          "tag": "path",
          "d": "M562.48,224.77c20.04,0,30.16-11.35,30.16-37.78s-10.11-37.78-30.16-37.78-30.16,11.35-30.16,37.78,10.11,37.78,30.16,37.78M562.48,123.48c45.94,0,65.63,18.98,65.63,63.51s-19.69,63.5-65.63,63.5-65.63-18.98-65.63-63.5,19.69-63.51,65.63-63.51"
        },
        {
          "tag": "polygon",
          "points": "699.21 124 732.91 239.3 733.98 239.3 733.98 124 766.62 124 766.62 248.17 702.76 248.17 669.06 132.86 667.99 132.86 667.99 248.17 635.35 248.17 635.35 124 699.21 124"
        },
        {
          "tag": "polygon",
          "points": "893.45 124 863.29 248.17 801.21 248.17 771.05 124 806.53 124 832.25 234.86 857.97 124 893.45 124"
        },
        {
          "tag": "polygon",
          "points": "993.88 124 993.88 148.83 933.57 148.83 933.57 171.89 986.79 171.89 986.79 196.72 933.57 196.72 933.57 223.33 993.88 223.33 993.88 248.17 898.1 248.17 898.1 124 993.88 124"
        },
        {
          "tag": "path",
          "d": "M1062.23,180.76c10.64,0,15.96-6.92,15.96-15.96s-5.32-15.96-15.96-15.96h-26.61v31.93h26.61ZM1064,124c35.48,0,49.67,19.51,49.67,40.8,0,15.79-6.38,28.2-22,34.59l25.55,48.96h-37.25l-20.4-44.52h-23.95v44.35h-35.48v-124.17h63.86Z"
        },
        {
          "tag": "polygon",
          "points": "1116.13 124 1116.13 152.38 1149.05 152.38 1149.05 248.17 1184.53 248.17 1184.53 152.38 1217.45 152.38 1217.45 124 1116.13 124"
        },
        {
          "tag": "rect",
          "x": "131.22",
          "y": "124.11",
          "width": "32.68",
          "height": "124.32"
        },
        {
          "tag": "rect",
          "x": "163.91",
          "y": "91.43",
          "width": "124.32",
          "height": "32.68"
        },
        {
          "tag": "rect",
          "x": "163.91",
          "y": "248.43",
          "width": "124.32",
          "height": "32.68"
        }
      ]
    }
  },
  {
    "id": "straight-svg-clear-space-convert-logo-straight-light-green-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "Light Green",
    "format": "svg",
    "clearSpace": true,
    "source": "Straight/SVG/Clear Space/Convert_Logo_Straight_Light Green_Clear Space.svg",
    "href": "/brand/logos/straight-svg-clear-space-convert-logo-straight-light-green-clear-space.svg",
    "bytes": 2009,
    "sha256": "dbd48c892e529d1f7ccfc4b29d987a3cfda4a0d2953b1448d7f4d97afa496815",
    "geometry": {
      "viewBox": "0 0 1348.68 372.53",
      "fill": "#c9deb6",
      "shapes": [
        {
          "tag": "path",
          "d": "M430.58,147.94c-20.05,0-28.38,11.17-28.38,37.96s8.34,37.78,28.38,37.78c14.9,0,22.17-5.5,24.83-18.98h35.48c-6.92,31.4-25.01,44.88-60.31,44.88-45.94,0-63.86-19.16-63.86-63.68s17.92-63.86,63.86-63.86c37.6,0,55.88,13.48,60.31,44.88h-35.48c-2.66-13.48-9.93-18.98-24.83-18.98"
        },
        {
          "tag": "path",
          "d": "M562.48,224.77c20.04,0,30.16-11.35,30.16-37.78s-10.11-37.78-30.16-37.78-30.16,11.35-30.16,37.78,10.11,37.78,30.16,37.78M562.48,123.48c45.94,0,65.63,18.98,65.63,63.51s-19.69,63.5-65.63,63.5-65.63-18.98-65.63-63.5,19.69-63.51,65.63-63.51"
        },
        {
          "tag": "polygon",
          "points": "699.21 124 732.91 239.3 733.98 239.3 733.98 124 766.62 124 766.62 248.17 702.76 248.17 669.06 132.86 667.99 132.86 667.99 248.17 635.35 248.17 635.35 124 699.21 124"
        },
        {
          "tag": "polygon",
          "points": "893.45 124 863.29 248.17 801.21 248.17 771.05 124 806.53 124 832.25 234.86 857.97 124 893.45 124"
        },
        {
          "tag": "polygon",
          "points": "993.88 124 993.88 148.83 933.57 148.83 933.57 171.89 986.79 171.89 986.79 196.72 933.57 196.72 933.57 223.33 993.88 223.33 993.88 248.17 898.1 248.17 898.1 124 993.88 124"
        },
        {
          "tag": "path",
          "d": "M1062.23,180.76c10.64,0,15.96-6.92,15.96-15.96s-5.32-15.96-15.96-15.96h-26.61v31.93h26.61ZM1064,124c35.48,0,49.67,19.51,49.67,40.8,0,15.79-6.38,28.2-22,34.59l25.55,48.96h-37.25l-20.4-44.52h-23.95v44.35h-35.48v-124.17h63.86Z"
        },
        {
          "tag": "polygon",
          "points": "1116.13 124 1116.13 152.38 1149.05 152.38 1149.05 248.17 1184.53 248.17 1184.53 152.38 1217.45 152.38 1217.45 124 1116.13 124"
        },
        {
          "tag": "rect",
          "x": "131.22",
          "y": "124.11",
          "width": "32.68",
          "height": "124.32"
        },
        {
          "tag": "rect",
          "x": "163.91",
          "y": "91.43",
          "width": "124.32",
          "height": "32.68"
        },
        {
          "tag": "rect",
          "x": "163.91",
          "y": "248.43",
          "width": "124.32",
          "height": "32.68"
        }
      ]
    }
  },
  {
    "id": "straight-svg-clear-space-convert-logo-straight-white-clear-space",
    "family": "Straight",
    "label": "Straight, clear space",
    "colour": "White",
    "format": "svg",
    "clearSpace": true,
    "source": "Straight/SVG/Clear Space/Convert_Logo_Straight_White_Clear Space.svg",
    "href": "/brand/logos/straight-svg-clear-space-convert-logo-straight-white-clear-space.svg",
    "bytes": 2009,
    "sha256": "185b9f93fb5db0a4eeb01d0192180a775113f41d0db8340fa970d6f3d95a3e71",
    "geometry": {
      "viewBox": "0 0 1348.68 372.53",
      "fill": "#faf9f7",
      "shapes": [
        {
          "tag": "path",
          "d": "M430.58,147.94c-20.05,0-28.38,11.17-28.38,37.96s8.34,37.78,28.38,37.78c14.9,0,22.17-5.5,24.83-18.98h35.48c-6.92,31.4-25.01,44.88-60.31,44.88-45.94,0-63.86-19.16-63.86-63.68s17.92-63.86,63.86-63.86c37.6,0,55.88,13.48,60.31,44.88h-35.48c-2.66-13.48-9.93-18.98-24.83-18.98"
        },
        {
          "tag": "path",
          "d": "M562.48,224.77c20.04,0,30.16-11.35,30.16-37.78s-10.11-37.78-30.16-37.78-30.16,11.35-30.16,37.78,10.11,37.78,30.16,37.78M562.48,123.48c45.94,0,65.63,18.98,65.63,63.51s-19.69,63.5-65.63,63.5-65.63-18.98-65.63-63.5,19.69-63.51,65.63-63.51"
        },
        {
          "tag": "polygon",
          "points": "699.21 124 732.91 239.3 733.98 239.3 733.98 124 766.62 124 766.62 248.17 702.76 248.17 669.06 132.86 667.99 132.86 667.99 248.17 635.35 248.17 635.35 124 699.21 124"
        },
        {
          "tag": "polygon",
          "points": "893.45 124 863.29 248.17 801.21 248.17 771.05 124 806.53 124 832.25 234.86 857.97 124 893.45 124"
        },
        {
          "tag": "polygon",
          "points": "993.88 124 993.88 148.83 933.57 148.83 933.57 171.89 986.79 171.89 986.79 196.72 933.57 196.72 933.57 223.33 993.88 223.33 993.88 248.17 898.1 248.17 898.1 124 993.88 124"
        },
        {
          "tag": "path",
          "d": "M1062.23,180.76c10.64,0,15.96-6.92,15.96-15.96s-5.32-15.96-15.96-15.96h-26.61v31.93h26.61ZM1064,124c35.48,0,49.67,19.51,49.67,40.8,0,15.79-6.38,28.2-22,34.59l25.55,48.96h-37.25l-20.4-44.52h-23.95v44.35h-35.48v-124.17h63.86Z"
        },
        {
          "tag": "polygon",
          "points": "1116.13 124 1116.13 152.38 1149.05 152.38 1149.05 248.17 1184.53 248.17 1184.53 152.38 1217.45 152.38 1217.45 124 1116.13 124"
        },
        {
          "tag": "rect",
          "x": "131.22",
          "y": "124.11",
          "width": "32.68",
          "height": "124.32"
        },
        {
          "tag": "rect",
          "x": "163.91",
          "y": "91.43",
          "width": "124.32",
          "height": "32.68"
        },
        {
          "tag": "rect",
          "x": "163.91",
          "y": "248.43",
          "width": "124.32",
          "height": "32.68"
        }
      ]
    }
  },
  {
    "id": "straight-svg-convert-logo-straight-black",
    "family": "Straight",
    "label": "Straight",
    "colour": "Black",
    "format": "svg",
    "clearSpace": false,
    "source": "Straight/SVG/Convert_Logo_Straight_Black.svg",
    "href": "/brand/logos/straight-svg-convert-logo-straight-black.svg",
    "bytes": 2002,
    "sha256": "f6d4764696580f29a2ee8f2272f8b89fef9af37b134b7cee045c4b8da12269db",
    "geometry": {
      "viewBox": "0 0 1089.35 191.14",
      "fill": "#171717",
      "shapes": [
        {
          "tag": "path",
          "d": "M300.92,57.25c-20.05,0-28.38,11.17-28.38,37.96s8.34,37.78,28.38,37.78c14.9,0,22.17-5.5,24.83-18.98h35.48c-6.92,31.4-25.01,44.88-60.31,44.88-45.94,0-63.86-19.16-63.86-63.68s17.92-63.86,63.86-63.86c37.6,0,55.88,13.48,60.31,44.88h-35.48c-2.66-13.48-9.93-18.98-24.83-18.98"
        },
        {
          "tag": "path",
          "d": "M432.82,134.07c20.04,0,30.16-11.35,30.16-37.78s-10.11-37.78-30.16-37.78-30.16,11.35-30.16,37.78,10.11,37.78,30.16,37.78M432.82,32.79c45.94,0,65.63,18.98,65.63,63.51s-19.69,63.5-65.63,63.5-65.63-18.98-65.63-63.5,19.69-63.51,65.63-63.51"
        },
        {
          "tag": "polygon",
          "points": "569.55 33.3 603.25 148.6 604.32 148.6 604.32 33.3 636.96 33.3 636.96 157.47 573.1 157.47 539.39 42.17 538.33 42.17 538.33 157.47 505.69 157.47 505.69 33.3 569.55 33.3"
        },
        {
          "tag": "polygon",
          "points": "763.79 33.3 733.63 157.47 671.54 157.47 641.39 33.3 676.87 33.3 702.59 144.17 728.31 33.3 763.79 33.3"
        },
        {
          "tag": "polygon",
          "points": "864.22 33.3 864.22 58.13 803.91 58.13 803.91 81.19 857.13 81.19 857.13 106.03 803.91 106.03 803.91 132.64 864.22 132.64 864.22 157.47 768.43 157.47 768.43 33.3 864.22 33.3"
        },
        {
          "tag": "path",
          "d": "M932.56,90.06c10.64,0,15.96-6.92,15.96-15.96s-5.32-15.96-15.96-15.96h-26.61v31.93h26.61ZM934.34,33.3c35.48,0,49.67,19.51,49.67,40.8,0,15.79-6.38,28.2-22,34.59l25.55,48.96h-37.25l-20.4-44.52h-23.95v44.35h-35.48V33.3h63.86Z"
        },
        {
          "tag": "polygon",
          "points": "986.47 33.3 986.47 61.68 1019.39 61.68 1019.39 157.47 1054.87 157.47 1054.87 61.68 1087.79 61.68 1087.79 33.3 986.47 33.3"
        },
        {
          "tag": "rect",
          "x": "1.56",
          "y": "33.41",
          "width": "32.68",
          "height": "124.32"
        },
        {
          "tag": "rect",
          "x": "34.24",
          "y": ".73",
          "width": "124.32",
          "height": "32.68"
        },
        {
          "tag": "rect",
          "x": "34.24",
          "y": "157.73",
          "width": "124.32",
          "height": "32.68"
        }
      ]
    }
  },
  {
    "id": "straight-svg-convert-logo-straight-dark-green",
    "family": "Straight",
    "label": "Straight",
    "colour": "Dark Green",
    "format": "svg",
    "clearSpace": false,
    "source": "Straight/SVG/Convert_Logo_Straight_Dark Green.svg",
    "href": "/brand/logos/straight-svg-convert-logo-straight-dark-green.svg",
    "bytes": 2002,
    "sha256": "53253d87f62295ce8e946c1410e2a8f1c709fcefe0f0f6dd3308611da502ca4a",
    "geometry": {
      "viewBox": "0 0 1089.35 191.14",
      "fill": "#27382f",
      "shapes": [
        {
          "tag": "path",
          "d": "M300.92,57.25c-20.05,0-28.38,11.17-28.38,37.96s8.34,37.78,28.38,37.78c14.9,0,22.17-5.5,24.83-18.98h35.48c-6.92,31.4-25.01,44.88-60.31,44.88-45.94,0-63.86-19.16-63.86-63.68s17.92-63.86,63.86-63.86c37.6,0,55.88,13.48,60.31,44.88h-35.48c-2.66-13.48-9.93-18.98-24.83-18.98"
        },
        {
          "tag": "path",
          "d": "M432.82,134.07c20.04,0,30.16-11.35,30.16-37.78s-10.11-37.78-30.16-37.78-30.16,11.35-30.16,37.78,10.11,37.78,30.16,37.78M432.82,32.79c45.94,0,65.63,18.98,65.63,63.51s-19.69,63.5-65.63,63.5-65.63-18.98-65.63-63.5,19.69-63.51,65.63-63.51"
        },
        {
          "tag": "polygon",
          "points": "569.55 33.3 603.25 148.6 604.32 148.6 604.32 33.3 636.96 33.3 636.96 157.47 573.1 157.47 539.39 42.17 538.33 42.17 538.33 157.47 505.69 157.47 505.69 33.3 569.55 33.3"
        },
        {
          "tag": "polygon",
          "points": "763.79 33.3 733.63 157.47 671.54 157.47 641.39 33.3 676.87 33.3 702.59 144.17 728.31 33.3 763.79 33.3"
        },
        {
          "tag": "polygon",
          "points": "864.22 33.3 864.22 58.13 803.91 58.13 803.91 81.19 857.13 81.19 857.13 106.03 803.91 106.03 803.91 132.64 864.22 132.64 864.22 157.47 768.43 157.47 768.43 33.3 864.22 33.3"
        },
        {
          "tag": "path",
          "d": "M932.56,90.06c10.64,0,15.96-6.92,15.96-15.96s-5.32-15.96-15.96-15.96h-26.61v31.93h26.61ZM934.34,33.3c35.48,0,49.67,19.51,49.67,40.8,0,15.79-6.38,28.2-22,34.59l25.55,48.96h-37.25l-20.4-44.52h-23.95v44.35h-35.48V33.3h63.86Z"
        },
        {
          "tag": "polygon",
          "points": "986.47 33.3 986.47 61.68 1019.39 61.68 1019.39 157.47 1054.87 157.47 1054.87 61.68 1087.79 61.68 1087.79 33.3 986.47 33.3"
        },
        {
          "tag": "rect",
          "x": "1.56",
          "y": "33.41",
          "width": "32.68",
          "height": "124.32"
        },
        {
          "tag": "rect",
          "x": "34.24",
          "y": ".73",
          "width": "124.32",
          "height": "32.68"
        },
        {
          "tag": "rect",
          "x": "34.24",
          "y": "157.73",
          "width": "124.32",
          "height": "32.68"
        }
      ]
    }
  },
  {
    "id": "straight-svg-convert-logo-straight-light-green",
    "family": "Straight",
    "label": "Straight",
    "colour": "Light Green",
    "format": "svg",
    "clearSpace": false,
    "source": "Straight/SVG/Convert_Logo_Straight_Light Green.svg",
    "href": "/brand/logos/straight-svg-convert-logo-straight-light-green.svg",
    "bytes": 2002,
    "sha256": "60044c70c5bfdedd893a929e4ac86565dc9e543d34c3e7fd7bb410fc390d07db",
    "geometry": {
      "viewBox": "0 0 1089.35 191.14",
      "fill": "#c9deb6",
      "shapes": [
        {
          "tag": "path",
          "d": "M300.92,57.25c-20.05,0-28.38,11.17-28.38,37.96s8.34,37.78,28.38,37.78c14.9,0,22.17-5.5,24.83-18.98h35.48c-6.92,31.4-25.01,44.88-60.31,44.88-45.94,0-63.86-19.16-63.86-63.68s17.92-63.86,63.86-63.86c37.6,0,55.88,13.48,60.31,44.88h-35.48c-2.66-13.48-9.93-18.98-24.83-18.98"
        },
        {
          "tag": "path",
          "d": "M432.82,134.07c20.04,0,30.16-11.35,30.16-37.78s-10.11-37.78-30.16-37.78-30.16,11.35-30.16,37.78,10.11,37.78,30.16,37.78M432.82,32.79c45.94,0,65.63,18.98,65.63,63.51s-19.69,63.5-65.63,63.5-65.63-18.98-65.63-63.5,19.69-63.51,65.63-63.51"
        },
        {
          "tag": "polygon",
          "points": "569.55 33.3 603.25 148.6 604.32 148.6 604.32 33.3 636.96 33.3 636.96 157.47 573.1 157.47 539.39 42.17 538.33 42.17 538.33 157.47 505.69 157.47 505.69 33.3 569.55 33.3"
        },
        {
          "tag": "polygon",
          "points": "763.79 33.3 733.63 157.47 671.54 157.47 641.39 33.3 676.87 33.3 702.59 144.17 728.31 33.3 763.79 33.3"
        },
        {
          "tag": "polygon",
          "points": "864.22 33.3 864.22 58.13 803.91 58.13 803.91 81.19 857.13 81.19 857.13 106.03 803.91 106.03 803.91 132.64 864.22 132.64 864.22 157.47 768.43 157.47 768.43 33.3 864.22 33.3"
        },
        {
          "tag": "path",
          "d": "M932.56,90.06c10.64,0,15.96-6.92,15.96-15.96s-5.32-15.96-15.96-15.96h-26.61v31.93h26.61ZM934.34,33.3c35.48,0,49.67,19.51,49.67,40.8,0,15.79-6.38,28.2-22,34.59l25.55,48.96h-37.25l-20.4-44.52h-23.95v44.35h-35.48V33.3h63.86Z"
        },
        {
          "tag": "polygon",
          "points": "986.47 33.3 986.47 61.68 1019.39 61.68 1019.39 157.47 1054.87 157.47 1054.87 61.68 1087.79 61.68 1087.79 33.3 986.47 33.3"
        },
        {
          "tag": "rect",
          "x": "1.56",
          "y": "33.41",
          "width": "32.68",
          "height": "124.32"
        },
        {
          "tag": "rect",
          "x": "34.24",
          "y": ".73",
          "width": "124.32",
          "height": "32.68"
        },
        {
          "tag": "rect",
          "x": "34.24",
          "y": "157.73",
          "width": "124.32",
          "height": "32.68"
        }
      ]
    }
  },
  {
    "id": "straight-svg-convert-logo-straight-white",
    "family": "Straight",
    "label": "Straight",
    "colour": "White",
    "format": "svg",
    "clearSpace": false,
    "source": "Straight/SVG/Convert_Logo_Straight_White.svg",
    "href": "/brand/logos/straight-svg-convert-logo-straight-white.svg",
    "bytes": 2002,
    "sha256": "6fcf74dd4243be13d938082d095bedea749ac5adbc3e59bd6f5df1808d75fffb",
    "geometry": {
      "viewBox": "0 0 1089.35 191.14",
      "fill": "#faf9f7",
      "shapes": [
        {
          "tag": "path",
          "d": "M300.92,57.25c-20.05,0-28.38,11.17-28.38,37.96s8.34,37.78,28.38,37.78c14.9,0,22.17-5.5,24.83-18.98h35.48c-6.92,31.4-25.01,44.88-60.31,44.88-45.94,0-63.86-19.16-63.86-63.68s17.92-63.86,63.86-63.86c37.6,0,55.88,13.48,60.31,44.88h-35.48c-2.66-13.48-9.93-18.98-24.83-18.98"
        },
        {
          "tag": "path",
          "d": "M432.82,134.07c20.04,0,30.16-11.35,30.16-37.78s-10.11-37.78-30.16-37.78-30.16,11.35-30.16,37.78,10.11,37.78,30.16,37.78M432.82,32.79c45.94,0,65.63,18.98,65.63,63.51s-19.69,63.5-65.63,63.5-65.63-18.98-65.63-63.5,19.69-63.51,65.63-63.51"
        },
        {
          "tag": "polygon",
          "points": "569.55 33.3 603.25 148.6 604.32 148.6 604.32 33.3 636.96 33.3 636.96 157.47 573.1 157.47 539.39 42.17 538.33 42.17 538.33 157.47 505.69 157.47 505.69 33.3 569.55 33.3"
        },
        {
          "tag": "polygon",
          "points": "763.79 33.3 733.63 157.47 671.54 157.47 641.39 33.3 676.87 33.3 702.59 144.17 728.31 33.3 763.79 33.3"
        },
        {
          "tag": "polygon",
          "points": "864.22 33.3 864.22 58.13 803.91 58.13 803.91 81.19 857.13 81.19 857.13 106.03 803.91 106.03 803.91 132.64 864.22 132.64 864.22 157.47 768.43 157.47 768.43 33.3 864.22 33.3"
        },
        {
          "tag": "path",
          "d": "M932.56,90.06c10.64,0,15.96-6.92,15.96-15.96s-5.32-15.96-15.96-15.96h-26.61v31.93h26.61ZM934.34,33.3c35.48,0,49.67,19.51,49.67,40.8,0,15.79-6.38,28.2-22,34.59l25.55,48.96h-37.25l-20.4-44.52h-23.95v44.35h-35.48V33.3h63.86Z"
        },
        {
          "tag": "polygon",
          "points": "986.47 33.3 986.47 61.68 1019.39 61.68 1019.39 157.47 1054.87 157.47 1054.87 61.68 1087.79 61.68 1087.79 33.3 986.47 33.3"
        },
        {
          "tag": "rect",
          "x": "1.56",
          "y": "33.41",
          "width": "32.68",
          "height": "124.32"
        },
        {
          "tag": "rect",
          "x": "34.24",
          "y": ".73",
          "width": "124.32",
          "height": "32.68"
        },
        {
          "tag": "rect",
          "x": "34.24",
          "y": "157.73",
          "width": "124.32",
          "height": "32.68"
        }
      ]
    }
  }
]
