// Generated by scripts/build-partners.mjs from src/brand/partners.json. Do not edit.
import type { Partner } from './partner-types'

export const partners: readonly Partner[] = [
  {
    "id": "accessibe",
    "name": "accessiBe",
    "categories": [
      "Accessibility"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "addressfinder",
    "name": "Addressfinder",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "adobe-commerce-magento",
    "name": "Adobe Commerce (Magento)",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "adyen",
    "name": "Adyen",
    "categories": [
      "Payments & Checkout"
    ],
    "website": "https://www.adyen.com/en_AU/",
    "listing": "listed",
    "files": [
      {
        "file": "adyen-logo-green.png",
        "href": "/brand/partners/adyen-logo-green.png",
        "format": "png",
        "vector": false,
        "note": "Green",
        "image": {
          "href": "/brand/partners/adyen-logo-green.png",
          "format": "png",
          "width": 1000,
          "height": 323,
          "bytes": 4696
        },
        "originalOn": "light",
        "width": 1000,
        "height": 323,
        "bytes": 4696,
        "sha256": "a72c533de003779479f9dd16906fbb5779e5ab825f4da04bea4b61b28ce4d3fc"
      }
    ],
    "vector": null
  },
  {
    "id": "airwallex",
    "name": "Airwallex",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "akeneo",
    "name": "Akeneo",
    "categories": [
      "Product Data & PIM"
    ],
    "website": "https://www.akeneo.com",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "algolia",
    "name": "Algolia",
    "categories": [
      "Merchandising",
      "Search",
      "Personalisation"
    ],
    "website": "https://www.algolia.com",
    "listing": "listed",
    "files": [
      {
        "file": "algolia-logo-white.svg",
        "href": "/brand/partners/algolia-logo-white.svg",
        "format": "svg",
        "vector": true,
        "note": "White",
        "image": null,
        "originalOn": "dark",
        "width": 251,
        "height": 58,
        "bytes": 7861,
        "sha256": "69009f7819a5b433a837d0771765cfab785eb98ed785ba05996ae072ba2e5e06"
      }
    ],
    "vector": "algolia-logo-white.svg"
  },
  {
    "id": "allyant",
    "name": "Allyant",
    "categories": [
      "Accessibility"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "andzen",
    "name": "Andzen",
    "categories": [
      "Email & SMS"
    ],
    "website": "https://andzen.co/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "athos-commerce",
    "name": "Athos Commerce",
    "categories": [
      "Search",
      "Merchandising"
    ],
    "website": "https://athoscommerce.com/",
    "listing": "listed",
    "files": [
      {
        "file": "athos-commerce-original.png",
        "href": "/brand/partners/athos-commerce-original.png",
        "format": "png",
        "vector": false,
        "note": "Full colour",
        "image": {
          "href": "/brand/partners/athos-commerce-original.png",
          "format": "png",
          "width": 556,
          "height": 118,
          "bytes": 9450
        },
        "originalOn": "light",
        "width": 556,
        "height": 118,
        "bytes": 9450,
        "sha256": "399c6bbe7569eebbb59d0c859f2da897c384596fe305a88478e3179fb2f5317b"
      }
    ],
    "vector": null
  },
  {
    "id": "attentive",
    "name": "Attentive",
    "categories": [
      "Email & SMS"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "avalara",
    "name": "Avalara",
    "categories": [
      "Payments & Checkout"
    ],
    "website": "https://www.avalara.com",
    "listing": "listed",
    "files": [
      {
        "file": "avalara-logo-rgb.jpg",
        "href": "/brand/partners/avalara-logo-rgb.jpg",
        "format": "jpg",
        "vector": false,
        "note": "Full colour on white",
        "image": {
          "href": "/brand/partners/avalara-logo-rgb.jpg",
          "format": "jpg",
          "width": 986,
          "height": 612,
          "bytes": 83614
        },
        "originalOn": "light",
        "width": 986,
        "height": 612,
        "bytes": 83614,
        "sha256": "284c32c3830b472270454b4cd62fd3076a01d4ff099de722a02a1d03db5d8403"
      }
    ],
    "vector": null
  },
  {
    "id": "bigcommerce",
    "name": "BigCommerce",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "bloomreach",
    "name": "Bloomreach",
    "categories": [
      "Search",
      "Merchandising",
      "Personalisation",
      "Email & SMS"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "brauz",
    "name": "Brauz",
    "categories": [
      "Retail & Omnichannel"
    ],
    "website": "https://brauz.com/",
    "listing": "listed",
    "files": [
      {
        "file": "brauz-logo.png",
        "href": "/brand/partners/brauz-logo.png",
        "format": "png",
        "vector": false,
        "note": "Black",
        "image": {
          "href": "/brand/partners/brauz-logo.png",
          "format": "png",
          "width": 528,
          "height": 185,
          "bytes": 15338
        },
        "originalOn": "light",
        "width": 528,
        "height": 185,
        "bytes": 15338,
        "sha256": "f1e9849a52e15a6c279ae5d8bb69c4bf71583139d1e1f327bdbd5220426ff430"
      }
    ],
    "vector": null
  },
  {
    "id": "braze",
    "name": "Braze",
    "categories": [
      "Email & SMS"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "calibre9",
    "name": "Calibre9",
    "categories": [
      "SEO"
    ],
    "website": "https://calibrenine.com.au",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "celigo",
    "name": "Celigo",
    "categories": [
      "Infrastructure & Integration"
    ],
    "website": "https://www.celigo.com",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "channelengine",
    "name": "ChannelEngine",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "checkout-components",
    "name": "Checkout Components",
    "categories": [
      "Payments & Checkout"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "clearer",
    "name": "clearer.io",
    "categories": [
      "Search"
    ],
    "website": "https://clearer.io",
    "listing": "listed",
    "files": [
      {
        "file": "clearer-logo-stacked-white.png",
        "href": "/brand/partners/clearer-logo-stacked-white.png",
        "format": "png",
        "vector": false,
        "note": "White, stacked",
        "image": {
          "href": "/brand/partners/clearer-logo-stacked-white.png",
          "format": "png",
          "width": 1433,
          "height": 2068,
          "bytes": 72203
        },
        "originalOn": "light",
        "width": 1433,
        "height": 2068,
        "bytes": 72203,
        "sha256": "6d4f69df6c1c005b7006c41c2c8d5a6d9411da8c52f362093c8a56132682db71"
      }
    ],
    "vector": null
  },
  {
    "id": "clearsale",
    "name": "ClearSale",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "cloudinary",
    "name": "Cloudinary",
    "categories": [
      "Content Management"
    ],
    "website": "https://cloudinary.com/",
    "listing": "listed",
    "files": [
      {
        "file": "cloudinary-logo.png",
        "href": "/brand/partners/cloudinary-logo.png",
        "format": "png",
        "vector": false,
        "note": "White on blue",
        "image": {
          "href": "/brand/partners/cloudinary-logo.png",
          "format": "png",
          "width": 1014,
          "height": 360,
          "bytes": 4959
        },
        "originalOn": "light",
        "width": 1014,
        "height": 360,
        "bytes": 4959,
        "sha256": "ad0f8b30743076ed7bdfd185ce963afed93a96ee596948df473c992886076c6f"
      }
    ],
    "vector": null
  },
  {
    "id": "comestri",
    "name": "Comestri",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "commercetools",
    "name": "commercetools",
    "categories": [
      "Ecommerce Platforms"
    ],
    "website": "https://www.commercetools.com",
    "listing": "listed",
    "files": [
      {
        "file": "commercetools.svg",
        "href": "/brand/partners/commercetools.svg",
        "format": "svg",
        "vector": true,
        "note": "Navy",
        "image": null,
        "originalOn": "light",
        "width": 296,
        "height": 81,
        "bytes": 6694,
        "sha256": "d5b025db4496c4d1516cc9b2d179ece10dc9d7f2ebba5b2d044c3f067a1f1af5"
      }
    ],
    "vector": "commercetools.svg"
  },
  {
    "id": "constructor",
    "name": "Constructor",
    "categories": [
      "Search"
    ],
    "website": "https://constructor.com/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "contentful",
    "name": "Contentful",
    "categories": [
      "Content Management"
    ],
    "website": "https://www.contentful.com",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "contentsquare",
    "name": "Contentsquare",
    "categories": [
      "Analytics"
    ],
    "website": "https://contentsquare.com/",
    "listing": "listed",
    "files": [
      {
        "file": "contentsquare-wordmark-coral.png",
        "href": "/brand/partners/contentsquare-wordmark-coral.png",
        "format": "png",
        "vector": false,
        "note": "Coral wordmark",
        "image": {
          "href": "/brand/partners/contentsquare-wordmark-coral.png",
          "format": "png",
          "width": 1182,
          "height": 342,
          "bytes": 19380
        },
        "originalOn": "light",
        "width": 1182,
        "height": 342,
        "bytes": 19380,
        "sha256": "f18dcd0379a729ea883a545a3338cce31a94d77e2d2b33d9461bba9c0649a7f3"
      }
    ],
    "vector": null
  },
  {
    "id": "contentstack",
    "name": "Contentstack",
    "categories": [
      "Content Management"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "dotdigital",
    "name": "Dotdigital",
    "categories": [
      "Email & SMS"
    ],
    "website": "https://dotdigital.com/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "elephant-room",
    "name": "Elephant Room",
    "categories": [
      "Gifting"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "elevar",
    "name": "Elevar",
    "categories": [
      "CDP"
    ],
    "website": "https://www.audiense.com/products/audiense-online/",
    "listing": "listed",
    "files": [
      {
        "file": "elevar-embedded-raster.svg",
        "href": "/brand/partners/elevar-embedded-raster.svg",
        "format": "svg",
        "vector": false,
        "note": "Colour",
        "image": {
          "href": "/brand/partners/elevar-embedded-raster.png",
          "format": "png",
          "width": 640,
          "height": 254,
          "bytes": 19218
        },
        "originalOn": "light",
        "width": 320,
        "height": 180,
        "bytes": 26193,
        "sha256": "4c12edeabb8b419c4ad3438bfa0909a93a8d736832db3282df16f6d3361b80bd"
      },
      {
        "file": "audiense-elevar-lockup.png",
        "href": "/brand/partners/audiense-elevar-lockup.png",
        "format": "png",
        "vector": false,
        "note": "Audiense and Elevar lockup",
        "image": {
          "href": "/brand/partners/audiense-elevar-lockup.png",
          "format": "png",
          "width": 764,
          "height": 79,
          "bytes": 10399
        },
        "originalOn": "light",
        "width": 764,
        "height": 79,
        "bytes": 10399,
        "sha256": "c69292813e38dd976c128a8e80bdb099ec391e13707a38f37870c98609ffe2dc"
      }
    ],
    "vector": null
  },
  {
    "id": "fluent-commerce",
    "name": "Fluent Commerce",
    "categories": [
      "Retail & Omnichannel",
      "B2B & Marketplace"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "foursixty",
    "name": "Foursixty",
    "categories": [
      "Reviews & UGC"
    ],
    "website": "https://foursixty.com",
    "listing": "listed",
    "files": [
      {
        "file": "foursixty-logo.png",
        "href": "/brand/partners/foursixty-logo.png",
        "format": "png",
        "vector": false,
        "note": "Black",
        "image": {
          "href": "/brand/partners/foursixty-logo.png",
          "format": "png",
          "width": 2572,
          "height": 228,
          "bytes": 82702
        },
        "originalOn": "light",
        "width": 2572,
        "height": 228,
        "bytes": 82702,
        "sha256": "578654aec837af74b4b6ccfee31de903e267cd9af96ba1e86b346d7ebcf9c539"
      }
    ],
    "vector": null
  },
  {
    "id": "giftnote",
    "name": "GiftNote",
    "categories": [
      "Gifting"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "givex",
    "name": "Givex",
    "categories": [
      "Gifting"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "global-e",
    "name": "Global-e",
    "categories": [
      "Global Commerce"
    ],
    "listing": "listed",
    "files": [
      {
        "file": "global-e-logo-white.svg",
        "href": "/brand/partners/global-e-logo-white.svg",
        "format": "svg",
        "vector": true,
        "note": "White",
        "image": null,
        "originalOn": "dark",
        "width": 154,
        "height": 34,
        "bytes": 2936,
        "sha256": "91aceaf8f99bf3166a9c9ad8605e86f83d2eab9106ab95c201aa088be9fc6824"
      }
    ],
    "vector": "global-e-logo-white.svg"
  },
  {
    "id": "gorgias",
    "name": "Gorgias",
    "categories": [
      "Customer Service"
    ],
    "website": "https://www.gorgias.com/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "humii",
    "name": "humii",
    "categories": [],
    "listing": "listed",
    "files": [
      {
        "file": "humii.svg",
        "href": "/brand/partners/humii.svg",
        "format": "svg",
        "vector": true,
        "note": "Lilac",
        "image": null,
        "originalOn": "dark",
        "width": 320,
        "height": 180,
        "bytes": 2280,
        "sha256": "25dd9a1a0100301a88452eec59821271ab207f68d65dad260f64bf35734dc238"
      }
    ],
    "vector": "humii.svg"
  },
  {
    "id": "klarna",
    "name": "Klarna",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "klaviyo",
    "name": "Klaviyo",
    "categories": [
      "CRM",
      "Customer Service",
      "Email & SMS"
    ],
    "website": "https://www.klaviyo.com/au/",
    "listing": "listed",
    "files": [
      {
        "file": "klaviyo.svg",
        "href": "/brand/partners/klaviyo.svg",
        "format": "svg",
        "vector": true,
        "note": "Black",
        "image": null,
        "originalOn": "light",
        "width": 581,
        "height": 172,
        "bytes": 5633,
        "sha256": "f853f8387bedb9a72a9658a120ed01faf0f41de415aeac188dd6d7c42480e337"
      }
    ],
    "vector": "klaviyo.svg"
  },
  {
    "id": "krakend",
    "name": "KrakenD",
    "categories": [
      "Infrastructure & Integration"
    ],
    "website": "https://www.krakend.io",
    "listing": "listed",
    "files": [
      {
        "file": "krakend-logo-black.png",
        "href": "/brand/partners/krakend-logo-black.png",
        "format": "png",
        "vector": false,
        "note": "Black",
        "image": {
          "href": "/brand/partners/krakend-logo-black.png",
          "format": "png",
          "width": 8192,
          "height": 1582,
          "bytes": 271266
        },
        "originalOn": "light",
        "width": 8192,
        "height": 1582,
        "bytes": 271266,
        "sha256": "acddf7173c5ec3c0b8850639241ec7c9dcb36ce016773bc21e9004afbc62767e"
      }
    ],
    "vector": null
  },
  {
    "id": "lexer",
    "name": "Lexer",
    "categories": [
      "CDP"
    ],
    "website": "https://www.lexer.io/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "litecard",
    "name": "Litecard",
    "categories": [
      "Mobile App"
    ],
    "website": "https://litecard.com",
    "listing": "listed",
    "files": [
      {
        "file": "litecard-logo-black-orange.png",
        "href": "/brand/partners/litecard-logo-black-orange.png",
        "format": "png",
        "vector": false,
        "note": "Black and orange",
        "image": {
          "href": "/brand/partners/litecard-logo-black-orange.png",
          "format": "png",
          "width": 2500,
          "height": 833,
          "bytes": 58588
        },
        "originalOn": "light",
        "width": 2500,
        "height": 833,
        "bytes": 58588,
        "sha256": "4ea6ad62ee93df091413de747967d696bd69f0de7d95f9e5e0722af5620fee7f"
      }
    ],
    "vector": null
  },
  {
    "id": "loop",
    "name": "Loop",
    "categories": [
      "Returns"
    ],
    "website": "https://www.loopreturns.com/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "loop-subscriptions",
    "name": "Loop Subscriptions",
    "categories": [
      "Retention & Subscriptions"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "loqate",
    "name": "Loqate",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "loyaltylion",
    "name": "LoyaltyLion",
    "categories": [
      "Loyalty & Rewards"
    ],
    "website": "https://loyaltylion.com",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "make-retail",
    "name": "Make Retail",
    "categories": [
      "Retail & Omnichannel"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "marketplacer",
    "name": "Marketplacer",
    "categories": [
      "B2B & Marketplace"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "mirra",
    "name": "Mirra",
    "categories": [
      "Retail & Omnichannel"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "mparticle",
    "name": "mParticle",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "netlify",
    "name": "Netlify",
    "categories": [
      "Infrastructure & Integration"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "netsuite",
    "name": "NetSuite",
    "categories": [
      "ERP"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "nosto",
    "name": "Nosto",
    "categories": [
      "Personalisation",
      "Search",
      "Merchandising"
    ],
    "website": "https://nosto.com",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "okendo",
    "name": "Okendo",
    "categories": [
      "Reviews & UGC"
    ],
    "website": "https://okendo.io",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "omneo",
    "name": "Omneo",
    "categories": [
      "CDP"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "online-retailer",
    "name": "Online Retailer",
    "categories": [],
    "listing": "listed",
    "files": [
      {
        "file": "online-retailer-embedded-raster.svg",
        "href": "/brand/partners/online-retailer-embedded-raster.svg",
        "format": "svg",
        "vector": false,
        "note": "Black",
        "image": {
          "href": "/brand/partners/online-retailer-embedded-raster.png",
          "format": "png",
          "width": 399,
          "height": 174,
          "bytes": 17233
        },
        "originalOn": "light",
        "width": 167,
        "height": 72,
        "bytes": 23522,
        "sha256": "d51d739ce558825f5bbb063f5fc09a8ce9482096d76a632f6e03cc1dee467989"
      }
    ],
    "vector": null
  },
  {
    "id": "optimising",
    "name": "Optimising",
    "categories": [
      "SEO"
    ],
    "website": "https://www.optimising.com.au",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "optty",
    "name": "Optty",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "patchworks",
    "name": "Patchworks",
    "categories": [
      "Infrastructure & Integration"
    ],
    "website": "https://www.patchworks.io",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "pattern",
    "name": "Pattern",
    "categories": [
      "Conversion Optimisation",
      "Performance Marketing",
      "Analytics"
    ],
    "website": "https://au.pattern.com/",
    "listing": "listed",
    "files": [
      {
        "file": "pattern.svg",
        "href": "/brand/partners/pattern.svg",
        "format": "svg",
        "vector": true,
        "note": "Full colour",
        "image": null,
        "originalOn": "light",
        "width": 191,
        "height": 38,
        "bytes": 7461,
        "sha256": "9107c50e5a5edd8fb95ea6b8519e0ba3eb62fa2da40080ce3e8102beb547ff60"
      }
    ],
    "vector": "pattern.svg"
  },
  {
    "id": "payoneer",
    "name": "Payoneer",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "paysquad",
    "name": "Paysquad",
    "categories": [
      "Payments & Checkout"
    ],
    "website": "https://paysquad.co",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "plytix",
    "name": "Plytix",
    "categories": [
      "Product Data & PIM"
    ],
    "website": "https://www.plytix.com/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "prismic",
    "name": "Prismic",
    "categories": [
      "Content Management"
    ],
    "website": "https://prismic.io/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "reactiv",
    "name": "Reactiv",
    "categories": [
      "Mobile App"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "rebuy",
    "name": "Rebuy",
    "categories": [
      "Merchandising"
    ],
    "website": "https://www.rebuyengine.com",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "recharge",
    "name": "Recharge",
    "categories": [
      "Retention & Subscriptions"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "refundid",
    "name": "Refundid",
    "categories": [
      "Returns"
    ],
    "website": "https://refundid.com/im-a-business",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "reload-media",
    "name": "Reload Media",
    "categories": [
      "Performance Marketing"
    ],
    "website": "https://www.reloadmedia.com.au/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "returngo",
    "name": "ReturnGo",
    "categories": [
      "Returns"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "rise-ai",
    "name": "Rise.ai",
    "categories": [
      "Gifting"
    ],
    "website": "https://rise.ai",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "rivo",
    "name": "Rivo",
    "categories": [
      "Loyalty & Rewards"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "sanity",
    "name": "Sanity",
    "categories": [
      "Content Management"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "searchspring",
    "name": "Searchspring",
    "aka": "Now part of Athos Commerce",
    "categories": [
      "Search"
    ],
    "listing": "listed",
    "files": [
      {
        "file": "searchspring-logo-white.svg",
        "href": "/brand/partners/searchspring-logo-white.svg",
        "format": "svg",
        "vector": true,
        "note": "White",
        "image": null,
        "originalOn": "dark",
        "width": 304,
        "height": 62,
        "bytes": 6345,
        "sha256": "61f44a8bcc286e9c06247cf2f023280fd7b35670feb55c48654c2cc9249269d9"
      },
      {
        "file": "searchspring-logo-colour-embedded-raster.svg",
        "href": "/brand/partners/searchspring-logo-colour-embedded-raster.svg",
        "format": "svg",
        "vector": false,
        "note": "Colour",
        "image": {
          "href": "/brand/partners/searchspring-logo-colour-embedded-raster.png",
          "format": "png",
          "width": 640,
          "height": 208,
          "bytes": 4750
        },
        "originalOn": "light",
        "width": 320,
        "height": 180,
        "bytes": 6915,
        "sha256": "11f3d486cce23cb07d2287072e551a8efe130eb5769f20826c0eaf2f613e64f0"
      }
    ],
    "vector": "searchspring-logo-white.svg"
  },
  {
    "id": "shippit",
    "name": "Shippit",
    "categories": [
      "Shipping & Fulfilment"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "shipstation",
    "name": "ShipStation",
    "categories": [
      "Shipping & Fulfilment"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "shopify-plus",
    "name": "Shopify Plus",
    "categories": [
      "Ecommerce Platforms"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "shoplift",
    "name": "Shoplift",
    "categories": [
      "Conversion Optimisation"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "starshipit",
    "name": "Starshipit",
    "categories": [
      "Shipping & Fulfilment"
    ],
    "website": "https://starshipit.com/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "stockinstore",
    "name": "Stockinstore",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "stripe",
    "name": "Stripe",
    "categories": [
      "Payments & Checkout"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "studiohawk",
    "name": "Studiohawk",
    "categories": [
      "SEO"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "submarine",
    "name": "Submarine",
    "categories": [
      "Infrastructure & Integration"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "swap",
    "name": "Swap",
    "categories": [
      "Returns",
      "Global Commerce"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "swish",
    "name": "Swish",
    "categories": [
      "Personalisation"
    ],
    "website": "https://swish.app/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "swym",
    "name": "Swym",
    "categories": [
      "Personalisation"
    ],
    "website": "https://www.getswym.com",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "talon-one",
    "name": "Talon.One",
    "categories": [
      "Loyalty & Rewards"
    ],
    "website": "https://talon.one/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "tapcart",
    "name": "Tapcart",
    "categories": [
      "Mobile App"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "techweave",
    "name": "Techweave",
    "categories": [
      "Infrastructure & Integration"
    ],
    "listing": "unlisted",
    "files": [],
    "vector": null
  },
  {
    "id": "the-wishlist-company",
    "name": "The Wishlist Company",
    "categories": [
      "Personalisation"
    ],
    "website": "https://www.thewishlist.io",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "tolstoy",
    "name": "Tolstoy",
    "categories": [
      "Merchandising"
    ],
    "website": "https://www.gotolstoy.com",
    "listing": "listed",
    "files": [
      {
        "file": "tolstoy.svg",
        "href": "/brand/partners/tolstoy.svg",
        "format": "svg",
        "vector": true,
        "note": "Black",
        "image": null,
        "originalOn": "light",
        "width": 248,
        "height": 49,
        "bytes": 2778,
        "sha256": "c3c5559005f859180994890d63ea14ebb66328d5f65f9f0efeb77d772d6f738c"
      }
    ],
    "vector": "tolstoy.svg"
  },
  {
    "id": "triple-whale",
    "name": "Triple Whale",
    "categories": [
      "Analytics"
    ],
    "website": "https://www.triplewhale.com/",
    "listing": "listed",
    "files": [
      {
        "file": "triple-whale.svg",
        "href": "/brand/partners/triple-whale.svg",
        "format": "svg",
        "vector": true,
        "note": "Full colour",
        "image": null,
        "originalOn": "light",
        "width": 320,
        "height": 180,
        "bytes": 9422,
        "sha256": "d2bb04a1415ce06226095d0762d834c4c4dedd31144a3948f3ee0dcbb17a1ac6"
      }
    ],
    "vector": "triple-whale.svg"
  },
  {
    "id": "trustana",
    "name": "Trustana",
    "categories": [
      "B2B & Marketplace"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "vercel",
    "name": "Vercel",
    "categories": [
      "Infrastructure & Integration"
    ],
    "website": "https://vercel.com/",
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "worldpay",
    "name": "Worldpay",
    "categories": [
      "Payments & Checkout"
    ],
    "listing": "listed",
    "files": [],
    "vector": null
  },
  {
    "id": "yotpo",
    "name": "Yotpo",
    "categories": [
      "Reviews & UGC"
    ],
    "website": "https://yotpo.com",
    "listing": "listed",
    "files": [
      {
        "file": "yotpo-logo-white.svg",
        "href": "/brand/partners/yotpo-logo-white.svg",
        "format": "svg",
        "vector": true,
        "note": "White",
        "image": null,
        "originalOn": "dark",
        "width": 238,
        "height": 65,
        "bytes": 1644,
        "sha256": "ee2b4afa70cd3e1d30d8fc9ae8b088c2284293ea57ee2da4d6599c4f0173c97c"
      }
    ],
    "vector": "yotpo-logo-white.svg"
  },
  {
    "id": "zip",
    "name": "Zip",
    "categories": [],
    "listing": "unlisted",
    "files": [],
    "vector": null
  }
]
