// Generated by scripts/build-partners.mjs from src/brand/partners.json. Do not edit.
import type { Partner } from './partner-types'

export const partners: readonly Partner[] = [
  {
    "id": "adyen",
    "name": "Adyen",
    "files": [
      {
        "file": "adyen-logo-green.png",
        "href": "/brand/partners/adyen-logo-green.png",
        "format": "png",
        "vector": false,
        "note": "Green",
        "originalOn": "light",
        "width": 1000,
        "height": 323,
        "bytes": 4696,
        "sha256": "a72c533de003779479f9dd16906fbb5779e5ab825f4da04bea4b61b28ce4d3fc"
      }
    ],
    "vector": null
  },
  {
    "id": "algolia",
    "name": "Algolia",
    "files": [
      {
        "file": "algolia-logo-white.svg",
        "href": "/brand/partners/algolia-logo-white.svg",
        "format": "svg",
        "vector": true,
        "note": "White",
        "originalOn": "dark",
        "width": 251,
        "height": 58,
        "bytes": 7861,
        "sha256": "69009f7819a5b433a837d0771765cfab785eb98ed785ba05996ae072ba2e5e06"
      }
    ],
    "vector": "algolia-logo-white.svg"
  },
  {
    "id": "athos-commerce",
    "name": "Athos Commerce",
    "files": [
      {
        "file": "athos-commerce-original.png",
        "href": "/brand/partners/athos-commerce-original.png",
        "format": "png",
        "vector": false,
        "note": "Full colour",
        "originalOn": "light",
        "width": 556,
        "height": 118,
        "bytes": 9450,
        "sha256": "399c6bbe7569eebbb59d0c859f2da897c384596fe305a88478e3179fb2f5317b"
      }
    ],
    "vector": null
  },
  {
    "id": "avalara",
    "name": "Avalara",
    "files": [
      {
        "file": "avalara-logo-rgb.jpg",
        "href": "/brand/partners/avalara-logo-rgb.jpg",
        "format": "jpg",
        "vector": false,
        "note": "Full colour on white",
        "originalOn": "light",
        "width": 986,
        "height": 612,
        "bytes": 83614,
        "sha256": "284c32c3830b472270454b4cd62fd3076a01d4ff099de722a02a1d03db5d8403"
      }
    ],
    "vector": null
  },
  {
    "id": "brauz",
    "name": "Brauz",
    "files": [
      {
        "file": "brauz-logo.png",
        "href": "/brand/partners/brauz-logo.png",
        "format": "png",
        "vector": false,
        "note": "Black",
        "originalOn": "light",
        "width": 528,
        "height": 185,
        "bytes": 15338,
        "sha256": "f1e9849a52e15a6c279ae5d8bb69c4bf71583139d1e1f327bdbd5220426ff430"
      }
    ],
    "vector": null
  },
  {
    "id": "clearer",
    "name": "clearer.io",
    "files": [
      {
        "file": "clearer-logo-stacked-white.png",
        "href": "/brand/partners/clearer-logo-stacked-white.png",
        "format": "png",
        "vector": false,
        "note": "White, stacked",
        "originalOn": "light",
        "width": 1433,
        "height": 2068,
        "bytes": 72203,
        "sha256": "6d4f69df6c1c005b7006c41c2c8d5a6d9411da8c52f362093c8a56132682db71"
      }
    ],
    "vector": null
  },
  {
    "id": "cloudinary",
    "name": "Cloudinary",
    "files": [
      {
        "file": "cloudinary-logo.png",
        "href": "/brand/partners/cloudinary-logo.png",
        "format": "png",
        "vector": false,
        "note": "White on blue",
        "originalOn": "light",
        "width": 1014,
        "height": 360,
        "bytes": 4959,
        "sha256": "ad0f8b30743076ed7bdfd185ce963afed93a96ee596948df473c992886076c6f"
      }
    ],
    "vector": null
  },
  {
    "id": "commercetools",
    "name": "commercetools",
    "files": [
      {
        "file": "commercetools.svg",
        "href": "/brand/partners/commercetools.svg",
        "format": "svg",
        "vector": true,
        "note": "Navy",
        "originalOn": "light",
        "width": 296,
        "height": 81,
        "bytes": 6694,
        "sha256": "d5b025db4496c4d1516cc9b2d179ece10dc9d7f2ebba5b2d044c3f067a1f1af5"
      }
    ],
    "vector": "commercetools.svg"
  },
  {
    "id": "contentsquare",
    "name": "Contentsquare",
    "files": [
      {
        "file": "contentsquare-wordmark-coral.png",
        "href": "/brand/partners/contentsquare-wordmark-coral.png",
        "format": "png",
        "vector": false,
        "note": "Coral wordmark",
        "originalOn": "light",
        "width": 1182,
        "height": 342,
        "bytes": 19380,
        "sha256": "f18dcd0379a729ea883a545a3338cce31a94d77e2d2b33d9461bba9c0649a7f3"
      }
    ],
    "vector": null
  },
  {
    "id": "elevar",
    "name": "Elevar",
    "files": [
      {
        "file": "elevar-embedded-raster.svg",
        "href": "/brand/partners/elevar-embedded-raster.svg",
        "format": "svg",
        "vector": false,
        "note": "Colour",
        "originalOn": "light",
        "width": 320,
        "height": 180,
        "bytes": 26193,
        "sha256": "4c12edeabb8b419c4ad3438bfa0909a93a8d736832db3282df16f6d3361b80bd"
      },
      {
        "file": "audiense-elevar-lockup.png",
        "href": "/brand/partners/audiense-elevar-lockup.png",
        "format": "png",
        "vector": false,
        "note": "Audiense and Elevar lockup",
        "originalOn": "light",
        "width": 764,
        "height": 79,
        "bytes": 10399,
        "sha256": "c69292813e38dd976c128a8e80bdb099ec391e13707a38f37870c98609ffe2dc"
      }
    ],
    "vector": null
  },
  {
    "id": "foursixty",
    "name": "Foursixty",
    "files": [
      {
        "file": "foursixty-logo.png",
        "href": "/brand/partners/foursixty-logo.png",
        "format": "png",
        "vector": false,
        "note": "Black",
        "originalOn": "light",
        "width": 2572,
        "height": 228,
        "bytes": 82702,
        "sha256": "578654aec837af74b4b6ccfee31de903e267cd9af96ba1e86b346d7ebcf9c539"
      }
    ],
    "vector": null
  },
  {
    "id": "global-e",
    "name": "Global-e",
    "files": [
      {
        "file": "global-e-logo-white.svg",
        "href": "/brand/partners/global-e-logo-white.svg",
        "format": "svg",
        "vector": true,
        "note": "White",
        "originalOn": "dark",
        "width": 154,
        "height": 34,
        "bytes": 2936,
        "sha256": "91aceaf8f99bf3166a9c9ad8605e86f83d2eab9106ab95c201aa088be9fc6824"
      }
    ],
    "vector": "global-e-logo-white.svg"
  },
  {
    "id": "humii",
    "name": "humii",
    "files": [
      {
        "file": "humii.svg",
        "href": "/brand/partners/humii.svg",
        "format": "svg",
        "vector": true,
        "note": "Lilac",
        "originalOn": "dark",
        "width": 320,
        "height": 180,
        "bytes": 2280,
        "sha256": "25dd9a1a0100301a88452eec59821271ab207f68d65dad260f64bf35734dc238"
      }
    ],
    "vector": "humii.svg"
  },
  {
    "id": "klaviyo",
    "name": "Klaviyo",
    "files": [
      {
        "file": "klaviyo.svg",
        "href": "/brand/partners/klaviyo.svg",
        "format": "svg",
        "vector": true,
        "note": "Black",
        "originalOn": "light",
        "width": 581,
        "height": 172,
        "bytes": 5633,
        "sha256": "f853f8387bedb9a72a9658a120ed01faf0f41de415aeac188dd6d7c42480e337"
      }
    ],
    "vector": "klaviyo.svg"
  },
  {
    "id": "krakend",
    "name": "KrakenD",
    "files": [
      {
        "file": "krakend-logo-black.png",
        "href": "/brand/partners/krakend-logo-black.png",
        "format": "png",
        "vector": false,
        "note": "Black",
        "originalOn": "light",
        "width": 8192,
        "height": 1582,
        "bytes": 271266,
        "sha256": "acddf7173c5ec3c0b8850639241ec7c9dcb36ce016773bc21e9004afbc62767e"
      }
    ],
    "vector": null
  },
  {
    "id": "litecard",
    "name": "Litecard",
    "files": [
      {
        "file": "litecard-logo-black-orange.png",
        "href": "/brand/partners/litecard-logo-black-orange.png",
        "format": "png",
        "vector": false,
        "note": "Black and orange",
        "originalOn": "light",
        "width": 2500,
        "height": 833,
        "bytes": 58588,
        "sha256": "4ea6ad62ee93df091413de747967d696bd69f0de7d95f9e5e0722af5620fee7f"
      }
    ],
    "vector": null
  },
  {
    "id": "online-retailer",
    "name": "Online Retailer",
    "files": [
      {
        "file": "online-retailer-embedded-raster.svg",
        "href": "/brand/partners/online-retailer-embedded-raster.svg",
        "format": "svg",
        "vector": false,
        "note": "Black",
        "originalOn": "light",
        "width": 167,
        "height": 72,
        "bytes": 23522,
        "sha256": "d51d739ce558825f5bbb063f5fc09a8ce9482096d76a632f6e03cc1dee467989"
      }
    ],
    "vector": null
  },
  {
    "id": "pattern",
    "name": "Pattern",
    "files": [
      {
        "file": "pattern.svg",
        "href": "/brand/partners/pattern.svg",
        "format": "svg",
        "vector": true,
        "note": "Full colour",
        "originalOn": "light",
        "width": 191,
        "height": 38,
        "bytes": 7461,
        "sha256": "9107c50e5a5edd8fb95ea6b8519e0ba3eb62fa2da40080ce3e8102beb547ff60"
      }
    ],
    "vector": "pattern.svg"
  },
  {
    "id": "searchspring",
    "name": "Searchspring",
    "files": [
      {
        "file": "searchspring-logo-white.svg",
        "href": "/brand/partners/searchspring-logo-white.svg",
        "format": "svg",
        "vector": true,
        "note": "White",
        "originalOn": "dark",
        "width": 304,
        "height": 62,
        "bytes": 6345,
        "sha256": "61f44a8bcc286e9c06247cf2f023280fd7b35670feb55c48654c2cc9249269d9"
      },
      {
        "file": "searchspring-logo-colour-embedded-raster.svg",
        "href": "/brand/partners/searchspring-logo-colour-embedded-raster.svg",
        "format": "svg",
        "vector": false,
        "note": "Colour",
        "originalOn": "light",
        "width": 320,
        "height": 180,
        "bytes": 6915,
        "sha256": "11f3d486cce23cb07d2287072e551a8efe130eb5769f20826c0eaf2f613e64f0"
      }
    ],
    "vector": "searchspring-logo-white.svg"
  },
  {
    "id": "tolstoy",
    "name": "Tolstoy",
    "files": [
      {
        "file": "tolstoy.svg",
        "href": "/brand/partners/tolstoy.svg",
        "format": "svg",
        "vector": true,
        "note": "Black",
        "originalOn": "light",
        "width": 248,
        "height": 49,
        "bytes": 2778,
        "sha256": "c3c5559005f859180994890d63ea14ebb66328d5f65f9f0efeb77d772d6f738c"
      }
    ],
    "vector": "tolstoy.svg"
  },
  {
    "id": "triple-whale",
    "name": "Triple Whale",
    "files": [
      {
        "file": "triple-whale.svg",
        "href": "/brand/partners/triple-whale.svg",
        "format": "svg",
        "vector": true,
        "note": "Full colour",
        "originalOn": "light",
        "width": 320,
        "height": 180,
        "bytes": 9422,
        "sha256": "d2bb04a1415ce06226095d0762d834c4c4dedd31144a3948f3ee0dcbb17a1ac6"
      }
    ],
    "vector": "triple-whale.svg"
  },
  {
    "id": "yotpo",
    "name": "Yotpo",
    "files": [
      {
        "file": "yotpo-logo-white.svg",
        "href": "/brand/partners/yotpo-logo-white.svg",
        "format": "svg",
        "vector": true,
        "note": "White",
        "originalOn": "dark",
        "width": 238,
        "height": 65,
        "bytes": 1644,
        "sha256": "ee2b4afa70cd3e1d30d8fc9ae8b088c2284293ea57ee2da4d6599c4f0173c97c"
      }
    ],
    "vector": "yotpo-logo-white.svg"
  }
]
